### PR TITLE
feat: add contribution page

### PR DESCRIPTION
**Pull request by suzy-g38**
Add a contribution page.
Issue No: #285

**Description:**

I maintained the black and white theme and only hovering on the image will show color and clicking on it will take you to their github page.

**Contribution Page Screenshot.**

image

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
It appears that there is a bug in the codebase.
Screenshot from 2023-05-28 17-14-12
Since no search functionality is required, we can remove the search bar from that page. let's attempt to decrease the height and width of the contributor's badges.

**Comment by suzy-g38** [comment]
> It appears that there is a bug in the codebase. Screenshot from 2023-05-28 17-14-12 Since no search functionality is required, we can remove the search bar from that page. let's attempt to decrease the height and width of the contributor's badges.

Is this look good?

image

**Comment by JasonDsouza212** [comment]
The bug still exists because the width is 80 % make it 100%
.contributors-list {
  position: relative;
  list-style: none;
  margin: 0 auto;
  padding: 0;
  width: 80%;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: center;
  grid-gap: 3rem;
  margin-bottom: 5rem;
}

Additionally, you can enhance the appearance by adding padding of 0px 100px to adjust it accordingly to media queries. Furthermore, you can include a header stating "Our contributors".

**Comment by JasonDsouza212** [comment]
> > It appears that there is a bug in the codebase. Screenshot from 2023-05-28 17-14-12 Since no search functionality is required, we can remove the search bar from that page. let's attempt to decrease the height and width of the contributor's badges.
> 
> Is this look good?
> 
> image

This looks good but when I try to run your code Im not getting the result you mention instead Im getting
Screenshot from 2023-05-28 17-14-12

**Comment by suzy-g38** [comment]
> **The bug still exists because the width is 80 % make it 100%**
> 
> .contributors-list { position: relative; list-style: none; margin: 0 auto; padding: 0; width: 80%; display: flex; flex-direction: row; flex-wrap: wrap; justify-content: center; grid-gap: 3rem; margin-bottom: 5rem; }
> 
> Additionally, you can enhance the appearance by adding padding of 0px 100px to adjust it accordingly to media queries. Furthermore, you can include a header stating "Our contributors".

Please check it now I have made the changes that you suggested

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by suzy-g38** [comment]
@JasonDsouza212 can you add gssoc tag and the level of this issue

**Pull request merged**
