### PR TITLE
feat: Added a socials section and badges to that section in the readme

### LINKED ISSUE #1510: [Docs]:  Adding a socials section and badges to that section in the readme
### what's wrong in the documentation?

We should have a socials section in the readme. Example -

image

This would help you improve your project react and your social media profile as well.

### Add screenshots

added above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 1Shubham7**
## Related Issue

Closes #1510 

## Description

Added a socials section and added badges to it.

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by 1Shubham7** [comment]
@JasonDsouza212 Please review it, GSSoC'23 is about to end and I am among top 100, This will help me sustain it.

**Comment by JasonDsouza212** [comment]
@1Shubham7 change the url of linkedin from https://www.linkedin.com/in/https:/www.linkedin.com/in/jason-dsouza-130b421ba/ to
[https:/www.linkedin.com/in/jason-dsouza-130b421ba/](https://www.linkedin.com/in/jason-dsouza-130b421ba/)

**Comment by 1Shubham7** [comment]
Done @JasonDsouza212.

**Comment by 1Shubham7** [comment]
@JasonDsouza212 Please review it now, I have done as you said.

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the [CONTRIBUTING.md](https://github.com/JasonDsouza212/free-hit/blob/main/CONTRIBUTING.md) and change it accordingly.

**Comment by 1Shubham7** [comment]
Done @JasonDsouza212

**Pull request merged**
