### PR TITLE
feat: pagination feature added #1567

### PR DESCRIPTION
**Pull request by biplavmz**
pagination feature added #1567 

i am showing 18 userProfile after pagination click other 18 userProfile 

image

### CODE REVIEW

**Comment by biplavmz** [comment]
hii @JasonDsouza212 can you pls check and merge my pr

**Comment by JasonDsouza212** [comment]
Attach a screen recording that demonstrates the changes you made to the code, showing how it affects the application across all media widths.

**Comment by biplavmz** [comment]
hii @JasonDsouza212  pls check this 
https://github.com/JasonDsouza212/free-hit/assets/68702055/1c1ee067-0aee-4568-8888-53b416351cc8

**Comment by biplavmz** [comment]
hii @JasonDsouza212 pls check this
https://github.com/JasonDsouza212/free-hit/assets/68702055/df86ed26-af55-44f1-b7d2-1bcbb09b99db

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
