### PR TITLE
chore: Tools for image generation added #1227

### LINKED ISSUE #1227: [Adding Tool]: 8 tools under 'image generation'
### What tool are you adding and to what category?

We need to add 8 AI Tools under the category 'image generation'. 
<b>Related issue: #947 </b>
List of tools is :
<ol>
<li>PicFinder</li>
<li>Cutout Pro</li>
<li>ImagineMe</li>
<li>DeepAI</li>
<li>Pixray</li>
<li>Caryion</li>
<li>StarryAI</li>
<li>NIghtcafe</li>
</ol>

### Add Tool Link

Added tool links:
[PicFinder](https://picfinder.ai/)
[Cutout Pro](https://www.cutout.pro/)
[ImagineMe](https://imagineme.ai/)
[Pixray](https://replicate.com/pixray/text2image)
[DeepAI](https://deepai.org/machine-learning-model/text2img)
[Cariyon](https://www.craiyon.com/)
[StarryAI](https://starryai.com/)
[Nightcafe](https://creator.nightcafe.studio/text-to-image-art)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by inkerton**
## Related Issue

Closes #1227 

## Description

8 tools under category "image generation added". Now I will also add the category in filters.

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by inkerton** [comment]
please merge the pull request. 
Somebody made changes in the file and now its showing conflict.

**Comment by JasonDsouza212** [comment]
@inkerton there is no catagory called image generation so change that to tools

**Comment by inkerton** [comment]
> @inkerton there is no catagory called image generation so change that to tools

i added these tools for that purpose only. i'll add the category after adding the tools.

**Comment by inkerton** [comment]
> @inkerton there is no catagory called image generation so change that to tools

or do I make the category first.

**Comment by inkerton** [comment]
> @inkerton there is no catagory called image generation so change that to tools

Should I do it now?
I created a pull request earlier but you closed it so I added the tools first this time.

**Comment by JasonDsouza212** [comment]
@inkerton make the category as image_generation

**Comment by inkerton** [comment]
> @inkerton make the category as image_generation

the category name has been updated.
You can review the Pull Request now.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
