### PR TITLE
Added the friday.app , Ideasai and Merlin

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Hello Jason I have added Friday.app under useful tools, Ideasai under AI and Merlin under  extensions.

I have also shorten the links which is more good

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 is it alright?

**Comment by JasonDsouza212** [comment]
ideasai description is wrong so do check with it once

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 i am not able to find the good description of  ideasai can you help

**Comment by JasonDsouza212** [comment]
This platform helps you find the best ideas to start your startup

**Comment by Bharadwajshivam28** [comment]
> This platform helps you find the best ideas to start your startup

Okay

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 I have corrected the description of Ideasai

**Comment by JasonDsouza212** [comment]
Always attach the issue the pull request solves

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by Bharadwajshivam28** [comment]
cant understand please elaborate jason

**Comment by JasonDsouza212** [comment]
There will be an issue number associated with the issue. When creating a pull request , you need to address that issue by including its number in the description of the pull request. For example:
Closes: #163 #162 #161

**Pull request merged**
