### PR TITLE
Added list view in bookmarks page too

### LINKED ISSUE #465: [Feat]: List view in the Bookmarks section too
### What feature?

I have an idea 

Since we have a list as well as grid view in the tools section, I think that the list view should also be available in the saved bookmarks section. Currently the saved bookmarks can only be viewed in the grid view.

I'd like to work on this @JasonDsouza212 .

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mukul314**
## Related Issue

Closes #465 

## Description

 Now there is a list view in the bookmarks page too

Here is a video showing the list form in the bookmarks section:

https://github.com/JasonDsouza212/free-hit/assets/76463001/fe08264c-4c4b-4317-8d43-3398b23012fc

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Add a video and also resolve the conflicts

**Comment by mukul314** [comment]
@JasonDsouza212 , I've done the changes. Please review

**Comment by JasonDsouza212** [comment]
The height of the list is larger, so match it with the size of the list on the Home page.

**Comment by JasonDsouza212** [comment]
There are conflicts and also add screen recordings

**Comment by JasonDsouza212** [comment]
As this pull request is inactive, I'll be closing it.

**Pull request closed without merging**
