### PR TITLE
Removed emojis from header

### PR DESCRIPTION
**Pull request by priyankarpal**
Removed emojis from header
Updated NPM packages to new version

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
can you upload a screen shot

**Comment by priyankarpal** [comment]
> can you upload a screen shot

Just removed emojis from the header section.

image

**Comment by JasonDsouza212** [comment]
I think it's looking very empty

**Comment by priyankarpal** [comment]
> I think it's looks very empty

ok i will add more things

**Pull request closed without merging**
