### PR TITLE
Added Backend Section with 8 Tool

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue

https://github.com/JasonDsouza212/free-hit/issues/709

Closes #issue_number

## Description

I have created a new section where people can add new backend tools. Additionally, I have included eight useful tools that are widely used by backend developers.

## Screenshots

image

image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
please can you explain to me which rule I have not followed.  you have not told me clearly that makes me more confused

**Comment by bhavyanarnoli** [comment]
image
single ' should be there ig not ", im not sure of it though

**Comment by JasonDsouza212** [comment]
@Nishitbaria, the rule suggests that you should only make the changes mentioned in the issue. However, your PR modified the indentations, changed some tool URLs, added tools with lengthy descriptions, and did not shorten the image URLs. That's why it's important to read the README.md and CONTRIBUTING.md files carefully, as they provide a clear understanding of the guidelines. I recommend going through them line by line to ensure compliance.

**Comment by Nishitbaria** [comment]
so lets clear things : I have read  rules and I have mentioned in pull request  i am adding backend section with 8 tool  ,so I added backend category in categories.js,I have added backend tools in product.json,I added backend in filter this all was need for completing my issue,as from your feedback i will shorten image url and use short description  in my  upcoming change,please review it and merge it

**Comment by Nishitbaria** [comment]
@JasonDsouza212  Please review my PR

**Comment by JasonDsouza212** [comment]
@Nishitbaria, if you go to "Files Changed," you can compare the PR with the main branch. Your PR is changing indentations, other tool names, and many other things that cannot be accepted. Additionally, many tools are not free. Please go through it and see what changes you need to make so that I can merge the PR.

Screenshot from 2023-06-26 19-42-51

**Comment by Nishitbaria** [comment]
> @Nishitbaria, if you go to "Files Changed," you can compare the PR with the main branch. Your PR is changing indentations, other tool names, and many other things that cannot be accepted. Additionally, many tools are not free. Please go through it and see what changes you need to make so that I can merge the PR.
> 
> Screenshot from 2023-06-26 19-42-51

hey @JasonDsouza212  I make the necessary changes that you told me and the tool added by me are free to use by developers

**Comment by JasonDsouza212** [comment]
@Nishitbaria but you have deleted the tools, create a new PR with fresh start

**Comment by Nishitbaria** [comment]
> @Nishitbaria but you have deleted the tools, create a new PR with fresh start 

Do you mean I not include Backend tool in json ???

**Pull request closed without merging**
