### PR TITLE
fix: Bug issue 1594 BookMark Model added

### PR DESCRIPTION
**Pull request by biplavmz**
hii @JasonDsouza212 pls check and merge my code

image

image

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@biplavmz 
Attach a screen recording that demonstrates the changes you made to the code, showing how it affects the application across all media widths.

**Comment by biplavmz** [comment]
hii @JasonDsouza212  pls check this 
https://github.com/JasonDsouza212/free-hit/assets/68702055/84cd3222-a4a5-4ff8-a133-64b3b3f896a5

**Comment by JasonDsouza212** [comment]
@biplavmz I can see bugs in the changes , as well as problem with the cards

**Comment by biplavmz** [comment]
hii @JasonDsouza212 what problem

**Comment by JasonDsouza212** [comment]
@biplavmz the cards look larger and the model is supposed to look like a notification , and when clicked in mobile view we can see 2 models appear at the same time

**Comment by JasonDsouza212** [comment]
That kind of looks basic

**Comment by JasonDsouza212** [comment]
But as today is the last day for your contribution, do that

**Comment by JasonDsouza212** [comment]
Just create a new PR asap just adding alert

**Comment by biplavmz** [comment]
thanks @JasonDsouza212 i have added the pr pls check and merge

**Pull request closed without merging**
