### PR TITLE
Added logo in footer #330

### PR DESCRIPTION
**Pull request by Dimple-Choudhary**
Fixed: #330 

I have added a **logo** in the footer.

Kindly review and merge the PR

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Can you please provide screenshots from different media queries?

**Comment by Dimple-Choudhary** [comment]
I'm sorry, but I didn't understand what you exactly want, Am I  supposed to send you a screenshot of the responsiveness of the logo in the footer?

**Comment by JasonDsouza212** [comment]
I mean, can you upload screenshots of the footer in different screen widths, such as desktop view, tablet view, and mobile view?

**Comment by Dimple-Choudhary** [comment]
Okay! Here It Is
Different screen widths (1)

**Comment by JasonDsouza212** [comment]
You should have put the logo that I had sent you

**Comment by Dimple-Choudhary** [comment]
I apologize, may I attempt it once more?

**Comment by JasonDsouza212** [comment]
Yes you can do it , just edit this pr itself @Dimple-Choudhary

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
