### PR TITLE
feat: Update_product.json-1415

### PR DESCRIPTION
**Pull request by lakshmishreea122003**
## Related Issue

Closes [#1415](https://github.com/JasonDsouza212/free-hit/issues/1415)

## Description

Add broken-link-checker
It helps check your site for broken inbound and outbound links in seconds.

## Checklist

- [X ] My code adheres to the established style guidelines of the project.
- [X ] I have included comments in areas that may be difficult to understand.
- [X ] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003 attach the issue number the PR is supposed to close

**Comment by lakshmishreea122003** [comment]
I updated the PR name

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003 attach the issue number

**Comment by lakshmishreea122003** [comment]
I did attach the issue number

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
