### PR TITLE
style: #1220 position changed

### LINKED ISSUE #1220: [style]: position
### What's the style idea?

Here if we are changing the styles in position, and background, the page will look more responsive. Now when I am scrolling down, the whole page is moving, which depicts that the page is not responsive as much. If we are changing the styles in CSS, it will clear the issue

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by KavyaS5757**
## Related Issue

Closes #1220 

## Description

I have made the changes in the style section. Along the x-axis I made the overflow hidden and along the y-axis, it will scroll only, which won't allow the whole webpage to move when we are scrolling

## Checklist

- [x ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the [CONTRIBUTING.md](https://github.com/JasonDsouza212/free-hit/blob/main/CONTRIBUTING.md) and change it accordingly.
Add a screen recording in all media widths

**Comment by KavyaS5757** [comment]
Add new tool :
Go to src > DB > product.json & add your code

{
    productName: "< App_Name >",
    category: "remote | resume | tweet | ai | ethical | movies | extensions | tools",
    image: "< Image-Url >",
    link: "< Link_to_the_website >",
    description: "< Description of product >"
},

I'm confused about this step. Can you please explain this..?

**Comment by KavyaS5757** [comment]
Sir now all checks are passed and it's not showing an error

**Comment by KavyaS5757** [comment]
https://github.com/JasonDsouza212/free-hit/assets/113536933/b4df0ec0-d2d3-4124-8db5-3779715bafb3

**Pull request merged**
