### PR TITLE
chore:  added sejda #920

### LINKED ISSUE #920: [Feat]: Sejda: Online PDF editor
### What feature?

Edit & Sign PDF files online for free. Fill out PDF forms online. Change PDF text Add text to PDF. Edit existing PDF text. Add image to PDF Create links in PDF. Edit hyperlinks in PDF. Annotate PDF

### Add screenshots

Add screenshots
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deepshikha2708**
## Related Issue

Closes #920 

## Description

Added website for sejda, a pdf editing tool.

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by deepshikha2708** [comment]
will the pr title work now?

**Comment by priyankarpal** [comment]
> will the pr title work now?

it will be `chore: added tools name`

**Comment by deepshikha2708** [comment]
thanks a lot!!

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
