### PR TITLE
chore: added AI websites for Education #1108

### LINKED ISSUE #1108: [Adding Tool]: Useful AI Tools for Education
### What tool are you adding and to what category?

We need to add AI Tools for education like,

- Gradescope
- Ivy ChatBot
- Carnegie Learning
- Cognii, etc.

### Add Tool Link

Add tool link

- https://www.cognii.com/
- https://www.gradescope.com/
etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Related Issue - 1108

Closes #1108 

## Description
- Gradescope
- Ivy ChatBot
- Cognii
- Dragon Education
- Knowji
- Plaito
- Century AI Tools

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 please review this pr
I requested to add either `level-2` or `level-3` on this pr.

Thanks for assigning this task to me !

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney , the description should be less than 15 words

**Comment by JasonDsouza212** [comment]
> @JasonDsouza212 @VenomFate-619 please review this pr I requested to add either `level-2` or `level-3` on this pr.
> 
> Thanks for assigning this task to me!
Check out the latest Guthub discussion for recent announcements over this

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please add `gssoc23` and `level` labels on this pr so to come on the leaderboard

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, Thanks for merging this pr
please also add `gssoc23` and `level` labels on this pr so to come on the leaderboard

**Pull request merged**
