### PR TITLE
fix: corrected class error-messages #1556

### LINKED ISSUE #1556: [Bug]: class used instead of className and console.log messages still found
### What happened?

I found a BUG 🐞

### Add screenshots

Add screenshots
freehit

### What browsers are you seeing the problem on?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by youngancient**
## Related Issue

Closes #1556 

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by youngancient** [comment]
@VenomFate-619 Help review my PR

**Comment by JasonDsouza212** [comment]
@youngancient, you need to create the issue first. Afterward, you should attach the issue number to your pull request

**Comment by youngancient** [comment]
@JasonDsouza212 I did here: https://github.com/JasonDsouza212/free-hit/issues/1556#issue-1837875127

**Comment by JasonDsouza212** [comment]
@youngancient can you resolve the conflicts

**Pull request closed without merging**
