### PR TITLE
Refactor: use Search params for searching and clean the code in app component

### LINKED ISSUE #460: [Feat]: Clean the App component.
### What feature?

We can clean the App component and move the attributes and functions related to Home Page into the Home component and those related to the Bookmarks Page into Bookmark Component. The App component will just contain the Routes.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
I've removed the search feature from app component.
Also, I've changed the search feature to use query params and we will be adding `?q='search-value'` in the url.
Hence we don't have to use `useState` and `useEffect` hooks any more for searching and filtering purposes.
Also, this has fixed some of the bugs which were there in the search functionality.
Fixes #460

### CODE REVIEW

**Comment by VenomFate-619** [comment]
do mention for which issue this PR is for.

**Comment by kailashchoudhary11** [comment]
> do mention for which issue this PR is for.

Done

**Comment by JasonDsouza212** [comment]
@kailashchoudhary11 Everything is fine, but we are unable to obtain search suggestions.

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 Everything is fine, but we are unable to obtain search suggestions.

Yah, I removed it because it's not required. Since we are filtering the products on real time so there is no need of suggestions I think

**Comment by kailashchoudhary11** [comment]
Hey @JasonDsouza212 I've added the search suggestions option

**Comment by JasonDsouza212** [comment]
@kailashchoudhary11 When I select the option, it should only display the exact title that it matches.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
