### PR TITLE
Fixed the ChatGPT spelling it was CharGpt

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
@JasonDsouza212 Fixed the spelling sir

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 sir i fixed the spelling and also added SuperNormal, Magical and removal in ai category

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28  the image URLs seem to be very long. Use Bitly to shorten the URLs before uploading them, and then use the shortened link for the image

Okay sir

**Comment by JasonDsouza212** [comment]
@Bharadwajshivam28 you can call me Jason, no need to call sir

**Comment by Bharadwajshivam28** [comment]
ok jason

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
Looks good @Bharadwajshivam28

**Pull request merged**
