### PR TITLE
added html-css generator

### LINKED ISSUE #748: [Feat]: There is no html css generatoro from design
### What feature?

 i  will add this to front end tools https://html-css-js.com/css/generator/

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bhavyanarnoli**
## Related Issue

Closes #748 

## Description

I haave added {
    "productName": "Html-Css",
    "category": "web",
    "image": "https://contentstatic.techgig.com/thumb/msid-90265114,width-460,resizemode-4/How-CSS-JavaScript-HTML-make-the-best-combo-for-frontend-development.jpg?10356",
    "link": "https://html-css-js.com/css/generator/",
    "description": "It provides amazing and easy ui to convert design into frontend codes."
}, in the products part 

## Screenshots

image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.
- [x] Im gssoc contributor

### CODE REVIEW

**Comment by bhavyanarnoli** [comment]
image

**Comment by bhavyanarnoli** [comment]
@JasonDsouza212 pls review

**Comment by bhavyanarnoli** [comment]
done @JasonDsouza212

**Comment by VenomFate-619** [comment]
do edit the title of the PR such that it resembles with changes you made eg:- Added html-css-generator something like this.

for future contributions do remember to give the appropriate commit message

**Review by VenomFate-619 — APPROVED** [review]

**Comment by bhavyanarnoli** [comment]
@JasonDsouza212 pls merge

**Review by VenomFate-619 — APPROVED** [review]

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request closed without merging**
