### PR TITLE
Added Kayoanime website

### LINKED ISSUE #756: [Feat]: Add Kayoanime Website
### What feature?

I have an idea to add Kayoanime website.
Through this website the user can download any anime episode or watch it online.
Please assign me this issue under Gssoc'23.

### Add screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AlabhyaG**
## Related Issue

Closes #756 

## Description

Added kayoanime website

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by VenomFate-619** [comment]
add a shorten URL for the image

**Comment by JasonDsouza212** [comment]
use url shortner for Image URL

**Review by JasonDsouza212 — APPROVED** [review]

**Review by JasonDsouza212 — CHANGES_REQUESTED** [review]
Use URL shortner

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
