### PR TITLE
style: Grid view cards styling changed

### LINKED ISSUE #1222: [style]: Chaning UI of cards
### What's the style idea?

We need to improve  the ui of cards as it should be more eye pleasing and should give better user experience

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by M-A-N-I-K**
Cards styling in grid view changed

Closes #1222 

## Description

The current UI of cards is not very eye-pleasing and does not provide a good user experience. This pull request proposes to improve the UI of cards by making them more visually appealing and easier to use.

## Screenshots

image
image

# Responsiveness
image

## Checklist

- [x ] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@M-A-N-I-K the design still has many bugs

**Comment by M-A-N-I-K** [comment]
@JasonDsouza212 like what?

**Comment by JasonDsouza212** [comment]
Screenshot from 2023-07-08 19-19-30
Screenshot from 2023-07-08 19-19-06
As you can see, the navbar is not aligned and there is uneven spacing in the application. It has an entirely different style, and we need the card to have a minimalist and less animated design. For these reasons, we cannot move forward with this design.

**Comment by JasonDsouza212** [comment]
@M-A-N-I-K is not active I'll be closing this PR

**Pull request closed without merging**
