### PR TITLE
Feat : Category button selected feature

### PR DESCRIPTION
**Pull request by itsarraj**
Completed The Button Selected Feature

Screenshot from 2023-03-31 00-25-02

### CODE REVIEW

**Comment by itsarraj** [comment]
@JasonDsouza212 @gjha133 @esau-morais @agatha-chituwa @bobbyy16 
 Check my PR

**Comment by JasonDsouza212** [comment]
It seems like your branch wasn't updated to the new version of the code. So, please pull the latest changes and then create a pull request. The pull request you made is modifying the products.json, which is not what we want.

**Comment by itsarraj** [comment]
Okay , Will Look into it

**Comment by JasonDsouza212** [comment]
rest everything works good

**Comment by itsarraj** [comment]
@JasonDsouza212 Check Brother , Everything is Perfect Now

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
