### PR TITLE
responsiveness fixed for small devices

### LINKED ISSUE #558: [Feat]:  Button in the navbar of contact us
### What feature?

I have an idea to add a button in the navbar of contact us so that the user can directly get to the Contact us section.

And please assign this issue to me under GSOC.

### Add screenshots

Add screenshots
Screenshot 2023-06-10 014621

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #588: UI still not responsive for small devices[Bug]:
### What happened?

The UI is still not responsive for small devices like mobile phones.

### Add screenshots

Add screenshots
Screenshot 2023-06-12 125257
Screenshot 2023-06-12 125239
Screenshot 2023-06-12 125220

### What browsers are you seeing the problem on?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rahulrana701**
Closes #588 

## Description

I have fixed responsiveness for small devices , now it will be working fine on almost every small device.

## Screenshots

Screenshot 2023-06-17 130809

Screenshot 2023-06-17 130734

Screenshot 2023-06-17 130706

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 I have solved this issue , sorry earlier I unassigned myself by mistake , I hope you will understand , and consider this pull request.

**Comment by rahulrana701** [comment]
@JasonDsouza212 @VenomFate-619 will you consider this.

**Comment by VenomFate-619** [comment]
yes

**Comment by JasonDsouza212** [comment]
@rahulrana701, the issue you mentioned has been assigned to someone else, and this pull request does not address that particular issue. Could you please clarify what was wrong earlier?

**Comment by rahulrana701** [comment]
Hi @JasonDsouza212 this pull request mentions the correct issue which is related to responsiveness of the website in small devices , with this pull request I made the ui responsive for all small devices , I have mentioned the issue no in the pr as well , and earlier I created the same issue for responsiveness which was a high priority bug and create a pr for that but you said it was taken care of as it was a high priority bug , so I thought that issue was this , so by mistake I unassigned myself after that I came to know that it was different than it as this issue was for small devices , I hope you will understand and consider this pr as it is the second time I worked on an issue for a while and it was not considered 🫠🫠

**Comment by rahulrana701** [comment]
@JasonDsouza212 will you consider it

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 I have update the issue number It was written by mistake you can check it out

**Comment by JasonDsouza212** [comment]
Done

**Comment by JasonDsouza212** [comment]
@rahulrana701 can you add a video of all media queries of all pages

**Comment by rahulrana701** [comment]
@JasonDsouza212 thankyou

**Comment by rahulrana701** [comment]
@JasonDsouza212 sure

**Comment by rahulrana701** [comment]
@JasonDsouza212 

https://github.com/JasonDsouza212/free-hit/assets/123585591/fa967321-ad40-4e18-ae97-e9923eb19d2a


it is working fine above 350px width , which will make this application run accurately on almost all devices.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
