### PR TITLE
fix: remove broken links, fix some links

### PR DESCRIPTION
**Pull request by suzy-g38**
Remove some broken links, like Pogo, and Soap2Day.
Fix some links that were half-written, like Pika Style, Code Beautify, and 100L5.
Other links are alright.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
https://pogolinks.art/   - Pogolink
https://ww.soap2dayfree.net/home/  - soap today

**Comment by JasonDsouza212** [comment]
you can add these links to pogolinks and soap2day

**Review by suzy-g38 — COMMENTED** [review]
I have added both links(pogo and soap2day)

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
@suzy-g38 thank you for your contribution

**Pull request merged**
