### PR TITLE
Removed console.log messages

### LINKED ISSUE #508: [Bug]: Remove console.log messages
### What happened?

There are console.log messages in the code which are displayed on the browser console.

### Add screenshots

Screenshot (459)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Avinash905**
### Fixes issue:
Closes #508 

### Description:
Removed the console.log message from the code which were displayed on the browser console.

### CODE REVIEW

**Comment by VenomFate-619** [comment]
resolve the conflicts and do remove that change of index.html file

**Comment by JasonDsouza212** [comment]
@Avinash905 this branch has conflicts

**Comment by Avinash905** [comment]
> @Avinash905 this branch has conflicts

I'll resolve them

**Comment by JasonDsouza212** [comment]
@Avinash905 , I don't see any changes in the file

**Comment by Avinash905** [comment]
> @Avinash905 , I don't see any changes in the file

1st commit has the changes. 2nd commit is for resolving merge conflicts.

**Comment by JasonDsouza212** [comment]
create a new PR

**Comment by Avinash905** [comment]
You may close this because this is already been resolved

**Pull request closed without merging**
