### PR TITLE
chore: mapban.gg for eSports category

### LINKED ISSUE #1577: [Adding Tool]: Adding mapban.gg for eSports category
### What tool are you adding and to what category?

We need to add new category of eSports and in that mapban is a website that helps you to manage eSports competition for map veto in various multiplayer games like CS:GO, VALORANT, R6, etc.

Assign this issue to me under gssoc.

### Add Tool Link

Add tool link
Tool link: https://www.mapban.gg/en

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by rutujp78**
Adding the mapban.gg for eSports Category.

## Related Issue

Closes #1577 

## Description
Adding eSports category and adding mapban.gg tool in it.

## Screenshots

https://github.com/JasonDsouza212/free-hit/assets/76244494/11187fb5-cadf-4ba9-8b99-1f442efa4c54

## Checklist

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@rutujp78, a category should have at least 8 tools to be considered a valid category.

**Comment by rutujp78** [comment]
@JasonDsouza212 Please review this PR. I have added more tool in eSports category.

**Comment by rutujp78** [comment]
@JasonDsouza212 Check this PR, I have added more tools for eSports category.

**Comment by JasonDsouza212** [comment]
@rutujp78 are all the tools free

**Comment by rutujp78** [comment]
> @rutujp78 are all the tools free

@JasonDsouza212 Main functionality of tools is free to use but for some tools for extra features premium membership is available.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
