### PR TITLE
fix: responsiveness in the mobile view

### LINKED ISSUE #1389: [Bug]: Fixing the About page's contributor section
### What happened?

I found a BUG 🐞where the heading positioning, sizes, and styling look odd in the mobile view. 

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Viveksati5143**
## Related Issue

Closes #1389 

## Description

Fixed the heading positioning, sizes, and styling that looked odd in the mobile view of about's page contributor section

## Screenshots
image
image
image
image
image

## Checklist

- [X] My code adheres to the established style guidelines of the project.
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Add a screen recording in all media widths

**Comment by Viveksati5143** [comment]
> Add a screen recording in all media widths

screenrecording was too large to upload so here are all the ss.

**Comment by JasonDsouza212** [comment]
@Viveksati5143, the mobile view cards do not appear the same as before. Please work on that aspect.

**Comment by Viveksati5143** [comment]
image
image
image
image
image
image

**Comment by JasonDsouza212** [comment]
@Viveksati5143 The first card's background is not properly set in dark mode

**Pull request closed without merging**
