### PR TITLE
fix: #1310

### LINKED ISSUE #1310: [Adding Tool]:  sflix
### What tool are you adding and to what category?

We need to add sflix movie streaming website. It has almost old Bollywood and Hollywood movies too which we can watch for free. We should add this movies category.

### Add Tool Link

Add tool link: - https://sflix.to/home

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by vats147**
## Related Issue

Closes #1310 

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Parul1606** [comment]
@vats147 why are you working on this issue?

**Comment by vats147** [comment]
Should i not???

**Comment by JasonDsouza212** [comment]
@vats147 the issue specified is closed and there is no website link associated in this PR

**Comment by JasonDsouza212** [comment]
create an issue before creating a PR

**Comment by vats147** [comment]
Actually issue is closed you can check now: #1310

**Comment by JasonDsouza212** [comment]
@vats147 create a new Issue

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
