### PR TITLE
style: button hover in the title section #1246

### LINKED ISSUE #1246: [style]: button hover
### What's the style idea?

We need to improve  the hovering of numbers in the title section 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by harshita-2003**
## Related Issue

Closes #1246 

## Screenshots

https://github.com/JasonDsouza212/free-hit/assets/119532943/a3000c11-928a-4838-9564-5dcd6b20c56e

## Checklist

- [ x] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [ x] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The shadow effect does not look good. Instead, consider adding a subtle scaling effect.

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the [CONTRIBUTING.md](https://github.com/JasonDsouza212/free-hit/blob/main/CONTRIBUTING.md) and change it accordingly.

**Comment by harshita-2003** [comment]
Do acknowledge @JasonDsouza212 

https://github.com/JasonDsouza212/free-hit/assets/119532943/c8cbef4e-82f4-4e24-91a2-068194e19ef4

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by harshita-2003** [comment]
do merge this !

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
