### PR TITLE
chore: added Recorders #1020 

### LINKED ISSUE #1020: [Adding Tool]: Screen recorder applications
### What tool are you adding and to what category?

We need to add

- i-top screen recorder application.
- bandicam screen recorder application.
- cam-studio recorder application.
- Filmora application.
and many more.

### Add Tool Link

Add tool link

- [iTop Screen Recorder](https://recorder.itopvpn.com/)

I will add other application links in repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Related Issue - 1020

Closes #1020 

## Description
- i-top screen recorder application.
- bandicam screen recorder application.
- cam-studio recorder application.
- Filmora application.
- ScreenCast
- Camtasia
- ShareX

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 Sirs, please review this pr.
I requested to add either `level-2` or `level-3` on this pr

Thanks for assigning me this task !

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney is all Applications free to use

**Comment by JasonDsouza212** [comment]
> @Avdhesh-Varshney the Title should be at max 2 words

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please again review this pr

**Comment by VenomFate-619** [comment]
@Avdhesh-Varshney resolve the conflicts

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
