### PR TITLE
feat#541 Add new tool

### LINKED ISSUE #541: [Feat]: I want to add an Online code Editor
### What feature?

I want to add a new online code editor  repl.it where people can code .
 they have old-spec laptops and PC  and share their code with others via an online link 

### Add screenshots

Add screenshots
Screenshot 2023-06-09 095202

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Gurnav224**
## Related Issus

Add new tool repl.it
Closes #541 

## Description

Replit, formerly Repl.it, is a San Francisco-based start-up and an online integrated development environment. Replit being Software as a service allows users to create online projects and write code

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@Gurnav224 The tool is supposed to be added at the last

**Comment by Gurnav224** [comment]
Ok  I move to it to last

**Comment by JasonDsouza212** [comment]
ok @Gurnav224

**Comment by JasonDsouza212** [comment]
As there is no reply , Ill be closing this PR

**Comment by Gurnav224** [comment]
I fix the the code move my tool to the last

**Pull request closed without merging**
