### PR TITLE
responsiveness of the website fixed

### LINKED ISSUE #557: Website UI not responsive [Bug]:
### What happened?

The UI of the website is not responsive it is breaking at some points , I would like to make it completely responsive at all widths.

### Add screenshots

Add screenshots
<div class='d-flex'>
Screenshot 2023-06-10 001640
Screenshot 2023-06-10 001707
Screenshot 2023-06-10 001747
</div>

### What browsers are you seeing the problem on?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rahulrana701**
Closes #557

## Description
I have fixed the website responsiveness and  now it is completely responsive , it will work fine on almost all devices.

## Screenshots
Screenshot 2023-06-11 164712

Screenshot 2023-06-11 164734

Screenshot 2023-06-11 164749

Screenshot 2023-06-11 164811

### CODE REVIEW

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 I have created a pull request for this issue , had to do a lot of work on this , as the css written for this 
section was very wrong and I had fixed the css as well as  made it responsive  , made navbar icons responsive as well
and the footer as well. Thankyou...

**Comment by JasonDsouza212** [comment]
The design is not proper and has many bugs.
Screenshot from 2023-06-11 22-20-05

**Comment by rahulrana701** [comment]
@JasonDsouza212 done

**Comment by JasonDsouza212** [comment]
As the issue was of high priority, it has been taken care of.

**Comment by JasonDsouza212** [comment]
Thank you for your time

**Comment by rahulrana701** [comment]
@JasonDsouza212 will I get no points for this one ??

**Comment by rahulrana701** [comment]
@JasonDsouza212 The UI is still not responsive 
Screenshot 2023-06-12 125257
Screenshot 2023-06-12 125239

**Pull request closed without merging**
