### PR TITLE
feat: open graph image add

### LINKED ISSUE #1437: [Bug]: Existing open graph image is not working
### What happened?

OG graph image is not working or it's not present would like to fix that.
I would like to add a og graph image

### Add screenshots

Add screenshots
Screenshot 2023-07-20 at 11 37 42 AM

### What browsers are you seeing the problem on?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vatsalsinghkv**
## Related Issue

Closes #1437 

## Description

- Created a custom image for open graph tags.
- Added the image to the open graph tags.
- Fixed the head tag by pairing it with the closing tag.

## Image

Free tools that are free and helpful

## Screenshots

Screenshot 2023-07-21 at 10 31 53 AM

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@vatsalsinghkv can you change that to free-hit logo

**Comment by vatsalsinghkv** [comment]
@JasonDsouza212 check this one out.
Free tools that are free and helpful

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by vatsalsinghkv** [comment]
@JasonDsouza212 Sorry to inform you this now, but I hadn't updated the code with this image as I waiting for your confirmation before putting this image into the code 🥲

**Comment by JasonDsouza212** [comment]
Is it , try creating a new PR

**Pull request merged**
