### PR TITLE
ci: Create json-format.yml

### LINKED ISSUE #46: ci: add JSON formatter
- Need to add JSON format gh action

### PR DESCRIPTION
**Pull request by priyankarpal**
fixed #46

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Hey I understood this is important, can you explain to me what it exactly does because Im not familiar with this

**Comment by priyankarpal** [comment]
> Hey I understood this is important, can you explain to me what it exactly does because Im not familiar with this

OK ok, it will format our product.json code. If there is any error in json file it will show the error.

**Comment by JasonDsouza212** [comment]
ok then Ill merge it, Then I guess the product.js should be product.json

**Comment by priyankarpal** [comment]
> ok then Ill merge it, Then I guess the product.js should be product.json

yes

**Pull request closed without merging**
