### PR TITLE
Added lazy loading

### LINKED ISSUE #799: [Feat]: Add Lazy Loading
### What feature?

I have an idea to add lazy loading to the website. It will enhance the user experience. Please assign me this issue. Thank you!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sumitkr2000**
## Related Issue

Closes #799 

## Description

Hey, @JasonDsouza212 I have added lazy loading to the website. Please review my pr and merge it. Thank you!

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by sumitkr2000** [comment]
@JasonDsouza212 I have attached the video

**Comment by JasonDsouza212** [comment]
@sumitkr2000, I have reviewed the changes, but I don't think they contribute significantly to the application. In fact, adding them might make the application bulkier

**Comment by sumitkr2000** [comment]
Lazy loading improve the performance of website instead of making thm bulky. But if you think it's not required you can close this pr.

**Comment by sumitkr2000** [comment]
hey @JasonDsouza212 Are you going to merge this pr or not?

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
