### PR TITLE
style:Added hover effect to the social links #1237

### LINKED ISSUE #1237: [style]: Adding hover effects to the social links in the about page
### What's the style idea?

A small issue in which i would like to add hover effects to the social links in the cards on about page such that on hovering the twitter icon, the icon turn blue like the original logo, same for github and LinkedIn icon.

Also for the "learn more" button on the about page, I was thinking of adding some border radius and add some translation effect to the arrow on the button such that when we hover the button, it slightly translates to the right.

What do you think of these changes, please feel free to share your opinion.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Related Issue

Closes #1237 

## Description

Added appropriate hover effects to the social icons.

## Screenshots

https://www.awesomescreenshot.com/video/18920049?key=046955bfa87416e2863beb7d77464405

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@karthiknadar1204, the icons color is changing which is not needed so change them back to black itself

**Comment by karthiknadar1204** [comment]
Ok,border radius is fine for the buttons?

**Comment by karthiknadar1204** [comment]
@JasonDsouza212 Have reverted the colour change on hover,Only kept the changed border radius, pushing these changes

**Comment by karthiknadar1204** [comment]
Done, please review it whenever free

**Comment by karthiknadar1204** [comment]
@JasonDsouza212 Any update?

**Comment by karthiknadar1204** [comment]
@JasonDsouza212 Please review and merge this pr, Have other issues in the same project , don't want to pile up pr's so can start working on this after this one has been reviewed

**Comment by JasonDsouza212** [comment]
@karthiknadar1204, I apologize for the delayed response. If I don't reply here, please contact me directly on Twitter or Discord.

**Comment by karthiknadar1204** [comment]
@JasonDsouza212 Opening a new pr in a bit for the same issue, accidentally deleted the cloned file from my system, majorly focussed on adding a scaling effect to the social icons and adding some border radius to the buttons on the page so I don't the page width would matter here.



> Add a screen recording in all media widths

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the [CONTRIBUTING.md](https://github.com/JasonDsouza212/free-hit/blob/main/CONTRIBUTING.md) and change it accordingly.

**Comment by JasonDsouza212** [comment]
Add a screen recording in all media widths

**Comment by karthiknadar1204** [comment]
Will wrap up today

**Comment by karthiknadar1204** [comment]
Someone has already had their pr merged resolving the issue I wanted to work i.e the same pr, will work on something else

**Pull request closed without merging**
