### PR TITLE
fix: Showing Warning on search #1487

### LINKED ISSUE #1487: [Bug]: Showing Warning on search
### What happened?

I found a BUG 🐞
If we search for anything then we got a warning.

Can you assign me under GSSOC'23

### Add screenshots

Deceptive site ahead Warning

https://github.com/JasonDsouza212/free-hit/assets/90599826/f96531aa-f965-4833-9e9b-03ad85d9ac8e

### What browsers are you seeing the problem on?

Chrome, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by soubhik-111**
## Related Issue
Showing Warning on search
Closes #1487 

## Description
I have found corrupted images and fixed them.

## Screenshots

https://github.com/JasonDsouza212/free-hit/assets/90599826/8e7d2cb5-e788-4c0b-9d9f-c2ce1e592184

## Checklist

- [X] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by soubhik-111** [comment]
@JasonDsouza212 
Kindly merge it

**Comment by JasonDsouza212** [comment]
@soubhik-111 I dont think this can solve the issue you have addressed

**Comment by soubhik-111** [comment]
@JasonDsouza212 
Hello,
It already solved the issue I addressed how?
The answer is Browser have few security restriction which shows for corrupt or high risk route.
Therefore I have changed the images of the five which are found rish by Google console.
Thank You

**Comment by JasonDsouza212** [comment]
Screenshot from 2023-07-30 21-56-55
You have removed images of many tools can you add the images

**Pull request closed without merging**
