### PR TITLE
feat: Added Latest Ai Tools

### LINKED ISSUE #1146: [Adding Tool]:  Multiple AI Tools
### What tool are you adding and to what category?

We need to add Ai tools for generating websites and Images and Celebrity voice clones

### Add Tool Link

Midjourney : https://www.midjourney.com/
Lexica : https://lexica.art/
Framer : https://framer.ai/
UberDuck : https://uberduck.ai/
Reddit : https://reddit.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by AkshayPratapSingh09**
## Related Issue

Closes #1146

## Description

Need to add new and free latest AI tools so that Website should be more useful and sustainable to the visitors .

https://ibb.co/Xs2PNpS
https://ibb.co/JQXYdcZ
https://ibb.co/S7fprJc
https://ibb.co/nRdrH3N
https://ibb.co/d7GbThX

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by AkshayPratapSingh09** [comment]
@JasonDsouza212  Just added some latest tools to the site ...... hope you merge soon!

**Comment by AkshayPratapSingh09** [comment]
@JasonDsouza212  please label it as GSSOC23

**Comment by JasonDsouza212** [comment]
> @JasonDsouza212 please label it as GSSOC23

@AkshayPratapSingh09 , check Discussion for the latest update on this

**Comment by AkshayPratapSingh09** [comment]
@JasonDsouza212  ok then at least you can review it and merge it....I will try to find some betterment tomorrow. There is a lot of scope for redesigning..!

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
