### PR TITLE
Update Footer.css

### PR DESCRIPTION
**Pull request by lakshmishreea122003**
## Related Issue
Closes https://github.com/JasonDsouza212/free-hit/issues/826#issuecomment-1606217204

## Description
I have made changes in footer.css. This fixes the issue

## Checklist

- [x ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Can you add screen recordings in all media widths, please?

**Comment by JasonDsouza212** [comment]
Also attach the issue number at the top

**Comment by lakshmishreea122003** [comment]
> Can you add screen recordings in all media widths, please?

Here are the screenshots of the appearance of the site on different screen widths after changes :
 small screen
small screen

medium screen

medium1

large screen 

large1

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003, try it in your browser once and let me know if the issue persists

**Comment by lakshmishreea122003** [comment]
I have checked it in chrome browser and on gitpod, this updated code solves the issue https://github.com/JasonDsouza212/free-hit/issues/826#issuecomment-1606217204 .  
Here when only 1 item is displayed in ListView then the footer remains to the bottom instead of getting lifted as mentioned in the issue.

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
