### PR TITLE
style: Search Area Design Improvement

### LINKED ISSUE #817: [Feat]: Search Area Design Improvement
### What feature?

The current design is nice but it can be improved by working on the styling of this section. By adjusting some of the styling features of this section, I can make it look even better.

### Add screenshots

**Current Design**
freehit (3)

**Expected Updated Design**
freehit (2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iamRabia-N**
## Related Issue
Closes #817

## Description
Improvement in the search area design.

## Screenshots
ss

## Checklist
- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by iamRabia-N** [comment]
@JasonDsouza212

**Comment by JasonDsouza212** [comment]
@iamRabia-N add a screen recording in all media widths

**Comment by iamRabia-N** [comment]
@JasonDsouza212 [Screen Recording](https://drive.google.com/file/d/18PePyQ4154nRFfW5NWQmfFnK2ncB7Kvu/view?usp=sharing)

**Comment by JasonDsouza212** [comment]
@iamRabia-N, in the mobile view, the icon does not look good. It appears that its width is too wide, so please adjust it accordingly.After making the adjustment, please add a screen recording.

**Comment by iamRabia-N** [comment]
@JasonDsouza212 commit "e0a78d4f88bd96cc66df2371d6722e8f791e67dc" fulfilled changes in mobile mode.
[Screen Recording](https://drive.google.com/file/d/1ZcGgW74vgyiZ7XkSxRgjaHXIzwf-BJR-/view?usp=sharing)

**Comment by JasonDsouza212** [comment]
@iamRabia-N the icon still looks same

**Comment by iamRabia-N** [comment]
It's good on my side.

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the [CONTRIBUTING.md](https://github.com/JasonDsouza212/free-hit/blob/main/CONTRIBUTING.md) and change it accordingly.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
