### PR TITLE
Darkmode feature added in the whole website

### LINKED ISSUE #752: [Feat]: Dark mode button
### What feature?

I have an idea to implement a dark mode toggler button for the website

### Add screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Soumyajit2825**
## [Feat]: Dark mode button (Issue #752)

Closes #752 

## Description

- Created a smooth and unique dark-mode button using sun & moon emoji in the landing page
- Make the local storage option started for the website for dark-mode button (after refreshing the mode will be same as set by the user)
- Made this dark-mode using the available color-pallette in the website 
- Make some card heights fixed

## Screenshots

Screenshot 2023-06-23 175841
<br>

Screenshot 2023-06-23 175828

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

@JasonDsouza212 It's my first big-project. Thank-you for giving me some time to understand the code-base. I hope that you will like my work. If any changes needed you can ask me anytime
Thank You ❤️

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
include a screen recording of the full user interface

**Comment by Soumyajit2825** [comment]
> include a screen recording of the full user interface

You can check from the vercel-deployment right???

**Comment by Soumyajit2825** [comment]
https://github.com/JasonDsouza212/free-hit/assets/100519291/38bc2542-6caa-4477-8c7d-7e77845b92ec

@JasonDsouza212 Here it is

**Comment by JasonDsouza212** [comment]
@Soumyajit2825 as you can see the about page is not looking good

**Comment by Soumyajit2825** [comment]
> @Soumyajit2825 as you can see the about page is not looking good

If I change whole about page dark then it will look worse 😄 
Thats why I have changed just team part in the dark theme

**Comment by Soumyajit2825** [comment]
@JasonDsouza212 You can tell me what change is required in the About page

**Comment by Soumyajit2825** [comment]
@JasonDsouza212 Have you checked???
Please tell me if any changes needed
As far for the about page It's looking good
Cause by giving whole page dark theme it will not look good

**Comment by Soumyajit2825** [comment]
screencapture-localhost-5173-about-2023-06-24-11_10_06

I have tried this one @JasonDsouza212 

Just you check it and tell me is it ok??
Then I will commit it to the PR

**Comment by Soumyajit2825** [comment]
@JasonDsouza212 Hello!
Please tell me about this changes!!

**Comment by JasonDsouza212** [comment]
@Soumyajit2825 all the white thing should be black and all the black things should be white including images

**Comment by JasonDsouza212** [comment]
@Soumyajit2825 as you can see the space Below the contributors section is white which looks very odd

**Comment by Soumyajit2825** [comment]
> @Soumyajit2825 as you can see the space Below the contributors section is white which looks very odd

OK changing it

**Comment by Soumyajit2825** [comment]
> @Soumyajit2825 all the white thing should be black and all the black things should be white including images

yeah I have done it
Doing for the white space

**Comment by Soumyajit2825** [comment]
image

@JasonDsouza212 This is the design of the about page
The team section has been designed by that white space
That can't be changed
It's looking good if you see.
All the things are changing

**Comment by Soumyajit2825** [comment]
> screencapture-localhost-5173-about-2023-06-24-11_10_06
> 
> I have tried this one @JasonDsouza212
> 
> Just you check it and tell me is it ok?? Then I will commit it to the PR

This is the change I've done

**Comment by Soumyajit2825** [comment]
Sir, the thing is that white-space fixed in the design. It's not under any
section or div. The design is blank space where the team-boxes are floating.
I have changed all the things for the dark-mode including the back-to-top
button. It's looking good, looking unique actually.😇

**Comment by JasonDsouza212** [comment]
@Soumyajit2825, take your time and work on this. If the dark mode doesn't look good, we can't merge it. It should be good enough, which is why in the image, you can switch images in dark mode and make other necessary adjustments.

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
