### PR TITLE
fixes #488 

### LINKED ISSUE #488: [style]: Make the bookmarks page of greater size when no bookmarks are in sight so that the footer is not visible on on initial load
### What's the style idea?

setting minheight

### Add screenshots

Add screenshots
image

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rhithesh**
#488  
image
image

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@rhithesh the footer should be fixed at the end of the screen

**Comment by rhithesh** [comment]
@JasonDsouza212  didnt get you the footer is visible with scroll thanks.

**Comment by rhithesh** [comment]
@JasonDsouza212 please check thanks

**Comment by JasonDsouza212** [comment]
attach screen shots @rhithesh

**Comment by JasonDsouza212** [comment]
Since there is no response, I will be closing this issue.

**Pull request closed without merging**
