### PR TITLE
feat: search Feature Added #1544

### PR DESCRIPTION
**Pull request by biplavmz**
Contributor  Search Feature Added #1544 

search:-
image

when no contributor:-
image

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Attach a screen recording that demonstrates the changes you made to the code, showing how it affects the application across all media widths.

**Comment by biplavmz** [comment]
In mobile :- 
image

image

**Comment by biplavmz** [comment]
Hii @JasonDsouza212 only changes in the search contributor  section.

**Comment by JasonDsouza212** [comment]
Attach a screen recording that demonstrates the changes you made to the code, showing how it affects the application across all media widths.

**Comment by biplavmz** [comment]
Hii @JasonDsouza212  pls check

**Comment by biplavmz** [comment]
Hii @JasonDsouza212  pls check

https://github.com/JasonDsouza212/free-hit/assets/68702055/cd6985d0-217c-4f90-98a5-d2303ad50787

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
