### PR TITLE
added section

### PR DESCRIPTION
**Pull request by Esha-01**
## Related Issue

Closes #issue_number

## Checklist 

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] My changes have not introduced any new warnings.
- [ ] I have conducted a self-review of my code.
- [ ] 
FOOTER FREEHIT

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Add screenshots of all widths

**Comment by Esha-01** [comment]
> Add screenshots of all widths
can you explain what are you trying to say I didn't understand.

**Comment by Esha-01** [comment]
check it  i have updated the code

**Comment by kailashchoudhary11** [comment]
Hey @Esha-01 There are some issues in the code as the vercel is not able to deploy your code.

**Comment by JasonDsouza212** [comment]
@Esha-01 , What does the text area serve

**Comment by JasonDsouza212** [comment]
As the user is inactive we will be closing this PR

**Pull request closed without merging**
