### PR TITLE
Navbar more attractive

### PR DESCRIPTION
**Pull request by Ahtaxam**
#174 solved

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Can you add some screenshots of desktop and mobile view

**Comment by Ahtaxam** [comment]
Screenshot from 2023-04-30 09-08-32

Screenshot from 2023-04-30 09-07-49

**Comment by JasonDsouza212** [comment]
I think that the color is not matching with the theme

**Comment by Ahtaxam** [comment]
Sorry for late response. i did it intensionally to make search bar unique than header color. if we make it white than it does not look good

**Comment by JasonDsouza212** [comment]
As the UI has been changed, I suggest that you work on it. For this reason, I will be closing this pull request.

**Pull request closed without merging**
