### PR TITLE
chore: Name logo of FreeHit website, Fixes #804

### LINKED ISSUE #804: [style]: Make a name logo of the FreeHit website
### What's the style idea?

We need to improve  the logo of the website, which is very simple and the is written simply, I would like to design a name logo for the website. As active member of GSSOC'23 please assign me this issue.

### Add screenshots

Like this-
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Tisha6661**
## Related Issue

Closes #issue_number
#804 

## Description
Website new logo added in light and dark mode, as well as in navbar and footer.

## Screenshots
image
image

## Checklist
- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Can you also add screen recording in all the widths

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by Tisha6661** [comment]
I have made the logo responsive, but it was difficult to fit it in the mobile view with the search bar, so I have used a short part of logo, hope it is okay, here is the video-

https://github.com/JasonDsouza212/free-hit/assets/98682478/5ce0f2a5-bcbd-495f-aca5-691953b52475

**Comment by JasonDsouza212** [comment]
It doesn't look good in mobile view. One thing you can do is display the current logo in mobile view while allowing people using a desktop or tablet to see the logo you designed

**Comment by Tisha6661** [comment]
@JasonDsouza212 I have changed the mobile logo as you wished, here-

https://github.com/JasonDsouza212/free-hit/assets/98682478/28e9089c-2df1-4946-bc3f-89c7b0c3a782

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by Tisha6661** [comment]
@JasonDsouza212 Is it correct now?

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by Tisha6661** [comment]
> The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

What do I have to do, I didn't understand, please tell me.

**Comment by JasonDsouza212** [comment]
The logo is not aligning properly 
Screenshot from 2023-07-05 20-12-01

**Comment by Tisha6661** [comment]
@JasonDsouza212 Now is it all right-

https://github.com/JasonDsouza212/free-hit/assets/98682478/e70d51fc-ff7d-4c2c-9059-8dc18e0814e8

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
