### PR TITLE
FEAT: Add an auto suggestion feature in search-bar

### PR DESCRIPTION
**Pull request by SowreRajan-dev**
I have made a base for the feature which is assigned #186 . Here is the changes made.

https://user-images.githubusercontent.com/75199296/235455483-f7b0a860-eb2c-45ee-863e-017f783d8223.mp4

Let me know if any changes needed.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
that's really a very useful contribution @SowreRajan-dev 
Can you also add the screenshots of mobile view

**Comment by SowreRajan-dev** [comment]
> that's really a very useful contribution @SowreRajan-dev Can you also add the screenshots of mobile view

Galaxy-S9-Plus-S8-Plus-412x846

iPhone-8-7-6S-6-375x667

Medium-Screen-1024x800



Yes sure!. Here is the screenshots of mobile view @JasonDsouza212

**Comment by HarshPanchal26** [comment]
Hey @SowreRajan-dev  I also tried to did the same , the only thing where I stuck was the part where we need to present suggestion box in alphabetical order , Can you help me with this ?

**Comment by JasonDsouza212** [comment]
@SowreRajan-dev  give me some time. I will test the version and then merge it.

**Comment by JasonDsouza212** [comment]
@SowreRajan-dev can you also resolve the conflicts

**Comment by JasonDsouza212** [comment]
Yes @HarshPanchal26 , I think you both can work this out .

**Comment by JasonDsouza212** [comment]
Yes @HarshPanchal26 , I think you both can work this out .

**Comment by SowreRajan-dev** [comment]
> Hey @SowreRajan-dev , @JasonDsouza212 I found a one small error , Accidently if any user enters special special characters like : ., *, +, ?, ^, $, {, }, (, ), [, ], , and |. then our code base throws an error ,
> 
> Error is :
> 
> caught SyntaxError: Invalid regular expression: //: \ at end of pattern
> 
> I resolve it by making one change , I add another regular expression for it .
> 
> ```
>   const escapedSearchTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
>   const regex = new RegExp(escapedSearchTerm, 'gi');
> ```
> 
> Now this resolve it . Could you Please add it in your pull request .

Ok sure ill check for it

**Comment by SowreRajan-dev** [comment]
> Hey @SowreRajan-dev , @JasonDsouza212 I found a one small error , Accidently if any user enters special special characters like : ., *, +, ?, ^, $, {, }, (, ), [, ], , and |. then our code base throws an error ,
> 
> Error is :
> 
> caught SyntaxError: Invalid regular expression: //: \ at end of pattern
> 
> I resolve it by making one change , I add another regular expression for it .
> 
> ```
>   const escapedSearchTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
>   const regex = new RegExp(escapedSearchTerm, 'gi');
> ```
> 
> Now this resolve it . Could you Please add it in your pull request .

@HarshPanchal26  Can you add the screenshot/video of the error? brief out when it is occuring

**Comment by HarshPanchal26** [comment]
> > Hey @SowreRajan-dev , @JasonDsouza212 I found a one small error , Accidently if any user enters special special characters like : ., *, +, ?, ^, $, {, }, (, ), [, ], , and |. then our code base throws an error ,
> > Error is :
> > caught SyntaxError: Invalid regular expression: //: \ at end of pattern
> > I resolve it by making one change , I add another regular expression for it .
> > ```
> >   const escapedSearchTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
> >   const regex = new RegExp(escapedSearchTerm, 'gi');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now this resolve it . Could you Please add it in your pull request .
> 
> @HarshPanchal26 Can you add the screenshot/video of the error? brief out when it is occuring

@SowreRajan-dev   just type any special characters form above , and screen will be blank , Just try it and I will also upload the video in some time .

**Comment by SowreRajan-dev** [comment]
> > > Hey @SowreRajan-dev , @JasonDsouza212 I found a one small error , Accidently if any user enters special special characters like : ., *, +, ?, ^, $, {, }, (, ), [, ], , and |. then our code base throws an error ,
> > > Error is :
> > > caught SyntaxError: Invalid regular expression: //: \ at end of pattern
> > > I resolve it by making one change , I add another regular expression for it .
> > > ```
> > >   const escapedSearchTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
> > >   const regex = new RegExp(escapedSearchTerm, 'gi');
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Now this resolve it . Could you Please add it in your pull request .
> > 
> > @HarshPanchal26 Can you add the screenshot/video of the error? brief out when it is occuring .
> 
> @SowreRajan-dev   Don't worry about it much , it will only throw error if user accidently type  ' \ ' or ' ? ' in input box . For solution use the Regex from above , It will solve it .
> 
> Or  just let me know if above Regex don't work , I will fix it .

@HarshPanchal26 can you clone my pull request and try to fix that issue?

**Comment by HarshPanchal26** [comment]
> > > > Hey @SowreRajan-dev , @JasonDsouza212 I found a one small error , Accidently if any user enters special special characters like : ., *, +, ?, ^, $, {, }, (, ), [, ], , and |. then our code base throws an error ,
> > > > Error is :
> > > > caught SyntaxError: Invalid regular expression: //: \ at end of pattern
> > > > I resolve it by making one change , I add another regular expression for it .
> > > > ```
> > > >   const escapedSearchTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
> > > >   const regex = new RegExp(escapedSearchTerm, 'gi');
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Now this resolve it . Could you Please add it in your pull request .
> > > 
> > > 
> > > @HarshPanchal26 Can you add the screenshot/video of the error? brief out when it is occuring .
> > 
> > 
> > @SowreRajan-dev   Don't worry about it much , it will only throw error if user accidently type  ' \ ' or ' ? ' in input box . For solution use the Regex from above , It will solve it .
> > Or  just let me know if above Regex don't work , I will fix it .
> 
> @HarshPanchal26 can you clone my pull request and try to fix that issue?


@SowreRajan-dev  I clone your pull request ,This woks fine , I didn't get any error , Can you tell me which issue are you talking about .

**Comment by SowreRajan-dev** [comment]
> > > > > Hey @SowreRajan-dev , @JasonDsouza212 I found a one small error , Accidently if any user enters special special characters like : ., *, +, ?, ^, $, {, }, (, ), [, ], , and |. then our code base throws an error ,
> > > > > Error is :
> > > > > caught SyntaxError: Invalid regular expression: //: \ at end of pattern
> > > > > I resolve it by making one change , I add another regular expression for it .
> > > > > ```
> > > > >   const escapedSearchTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
> > > > >   const regex = new RegExp(escapedSearchTerm, 'gi');
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Now this resolve it . Could you Please add it in your pull request .
> > > > 
> > > > 
> > > > @HarshPanchal26 Can you add the screenshot/video of the error? brief out when it is occuring .
> > > 
> > > 
> > > @SowreRajan-dev   Don't worry about it much , it will only throw error if user accidently type  ' \ ' or ' ? ' in input box . For solution use the Regex from above , It will solve it .
> > > Or  just let me know if above Regex don't work , I will fix it .
> > 
> > 
> > @HarshPanchal26 can you clone my pull request and try to fix that issue?
> 
> @SowreRajan-dev I clone your pull request ,This woks fine , I didn't get any error , Can you tell me which issue are you talking about .

the same which you posted @HarshPanchal26

**Comment by SowreRajan-dev** [comment]
> > > > > Hey @SowreRajan-dev , @JasonDsouza212 I found a one small error , Accidently if any user enters special special characters like : ., *, +, ?, ^, $, {, }, (, ), [, ], , and |. then our code base throws an error ,
> > > > > Error is :
> > > > > caught SyntaxError: Invalid regular expression: //: \ at end of pattern
> > > > > I resolve it by making one change , I add another regular expression for it .
> > > > > ```
> > > > >   const escapedSearchTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
> > > > >   const regex = new RegExp(escapedSearchTerm, 'gi');
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Now this resolve it . Could you Please add it in your pull request .
> > > > 
> > > > 
> > > > @HarshPanchal26 Can you add the screenshot/video of the error? brief out when it is occuring .
> > > 
> > > 
> > > @SowreRajan-dev   Don't worry about it much , it will only throw error if user accidently type  ' \ ' or ' ? ' in input box . For solution use the Regex from above , It will solve it .
> > > Or  just let me know if above Regex don't work , I will fix it .
> > 
> > 
> > @HarshPanchal26 can you clone my pull request and try to fix that issue?
> 
> @SowreRajan-dev I clone your pull request ,This woks fine , I didn't get any error , Can you tell me which issue are you talking about .

I have fixed the escape character '\' error.

**Comment by SowreRajan-dev** [comment]
@JasonDsouza212 Can you check for the dependencies and merge them?
Kindly acknowledge me , if there are any changes.

**Comment by HarshPanchal26** [comment]
@SowreRajan-dev    I found something , whenever suggestion list appears and we select any of the suggestions from it ,technically suggestion box should have to disappear from page , It is what not happening with our pull request , I solved it ,

You haver to make minor changes in order to achieve it .

1 , In Header.css file 

Make one class called 

.display-none{
 display : none
} 

2 . In header.jsx


 const handleSuggestionClick = (value) => {
    document.getElementById('serch-suggestions').classList.add('diplay-none');
    setSearchTerm(value)
  }

  const handleChageInInput = (event)=>{
    setSearchTerm(event.target.value);
    let targetElem = document.getElementById('serch-suggestions');
    if( filteredSuggestions.length > 0 && targetElem.className.includes('diplay-none')){
      targetElem.classList.remove('diplay-none');
    }
  }
  
  
  // In Input box 
  
  <input
              type="text"
              placeholder=" Search for a tool or category..."
              value={searchTerm}
              // onChange={(e) => setSearchTerm(e.target.value)}
              onChange={(e)=> handleChageInInput(e)}
            />

Suggestion box now disappearing at a time user clicks on any of the suggestions 

Make sure to check this once . 

If not it not worked or any issue appears , Just let me know .

**Comment by SowreRajan-dev** [comment]
> @SowreRajan-dev I found something , whenever suggestion list appears and we select any of the suggestions from it ,technically suggestion box should have to disappear from page , It is what not happening with our pull request , I solved it ,
> 
> You haver to make minor changes in order to achieve it .
> 
> 1 , In Header.css file
> 
> Make one class called
> 
> .display-none{ display : none }
> 
> 2 . In header.jsx
> 
> const handleSuggestionClick = (value) => { document.getElementById('serch-suggestions').classList.add('diplay-none'); setSearchTerm(value) }
> 
> const handleChageInInput = (event)=>{ setSearchTerm(event.target.value); let targetElem = document.getElementById('serch-suggestions'); if( filteredSuggestions.length > 0 && targetElem.className.includes('diplay-none')){ targetElem.classList.remove('diplay-none'); } }
> 
> // In Input box
> 
> <input type="text" placeholder=" Search for a tool or category..." value={searchTerm} // onChange={(e) => setSearchTerm(e.target.value)} onChange={(e)=> handleChageInInput(e)} />
> 
> Suggestion box now disappearing at a time user clicks on any of the suggestions
> 
> Make sure to check this once .
> 
> If not it not worked or any issue appears , Just let me know .

Thanks for it. I ll update them in the codebase @HarshPanchal26

**Comment by HarshPanchal26** [comment]
> > @SowreRajan-dev    I found something , whenever suggestion list appears and we select any of the suggestions from it ,technically suggestion box should have to disappear from page , It is what not happening with our pull request , I solved it ,
> > You haver to make minor changes in order to achieve it .
> > 1 , In Header.css file
> > Make one class called
> > .display-none{
> > display : none
> > }
> > 2 . In header.jsx
> > const handleSuggestionClick = (value) => {
> > document.getElementById('serch-suggestions').classList.add('diplay-none');
> > setSearchTerm(value)
> > }
> > const handleChageInInput = (event)=>{
> > setSearchTerm(event.target.value);
> > let targetElem = document.getElementById('serch-suggestions');
> > if( filteredSuggestions.length > 0 && targetElem.className.includes('diplay-none')){
> > targetElem.classList.remove('diplay-none');
> > }
> > }
> > // In Input box
> > <input
> > type="text"
> > placeholder=" Search for a tool or category..."
> > value={searchTerm}
> > // onChange={(e) => setSearchTerm(e.target.value)}
> > onChange={(e)=> handleChageInInput(e)}
> > />
> > Suggestion box now disappearing at a time user clicks on any of the suggestions
> > Make sure to check this once .
> > If not it not worked or any issue appears , Just let me know .
> 
> @HarshPanchal26 this code change shoes the error. Can you change them and push to my repo I'll willl update them?
> 
> https://github.com/SowreRajan-dev/free-hit

@SowreRajan-dev   Sure . 

I made to pull request 

https://github.com/SowreRajan-dev/free-hit/pull/1

https://github.com/SowreRajan-dev/free-hit/pull/2

Check once and if it throws any error , Let me know  .

**Comment by SowreRajan-dev** [comment]
> > > @SowreRajan-dev    I found something , whenever suggestion list appears and we select any of the suggestions from it ,technically suggestion box should have to disappear from page , It is what not happening with our pull request , I solved it ,
> > > You haver to make minor changes in order to achieve it .
> > > 1 , In Header.css file
> > > Make one class called
> > > .display-none{
> > > display : none
> > > }
> > > 2 . In header.jsx
> > > const handleSuggestionClick = (value) => {
> > > document.getElementById('serch-suggestions').classList.add('diplay-none');
> > > setSearchTerm(value)
> > > }
> > > const handleChageInInput = (event)=>{
> > > setSearchTerm(event.target.value);
> > > let targetElem = document.getElementById('serch-suggestions');
> > > if( filteredSuggestions.length > 0 && targetElem.className.includes('diplay-none')){
> > > targetElem.classList.remove('diplay-none');
> > > }
> > > }
> > > // In Input box
> > > <input
> > > type="text"
> > > placeholder=" Search for a tool or category..."
> > > value={searchTerm}
> > > // onChange={(e) => setSearchTerm(e.target.value)}
> > > onChange={(e)=> handleChageInInput(e)}
> > > />
> > > Suggestion box now disappearing at a time user clicks on any of the suggestions
> > > Make sure to check this once .
> > > If not it not worked or any issue appears , Just let me know .
> > 
> > 
> > @HarshPanchal26 this code change shoes the error. Can you change them and push to my repo I'll willl update them?
> > https://github.com/SowreRajan-dev/free-hit
> 
> @SowreRajan-dev Sure .
> 
> I made to pull request
> 
> [SowreRajan-dev#1](https://github.com/SowreRajan-dev/free-hit/pull/1)
> 
> [SowreRajan-dev#2](https://github.com/SowreRajan-dev/free-hit/pull/2)
> 
> Check once and if it throws any error , Let me know .

Thank you @HarshPanchal26 . It worked.

**Comment by SowreRajan-dev** [comment]
@JasonDsouza212 can you check for the versions?

**Comment by JasonDsouza212** [comment]
Ok , Ill check with it once

**Comment by JasonDsouza212** [comment]
Looks good! Have you guys finished making your changes? Can I merge it now?

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
Thank you, @SowreRajan-dev and @HarshPanchal26  for your valuable contribution. That was a much-needed feature in the app. I hope you keep supporting and contributing to Free-hit to make it even better.

**Comment by SowreRajan-dev** [comment]
Its really a great experience and it is my first open source contribution. Thanks for @HarshPanchal26 helping me out!. Its really pleasure with working in this website. Thanks @JasonDsouza212 and @HarshPanchal26 for the support!.

**Comment by JasonDsouza212** [comment]
Indeed that was really a good start in your open source journey @SowreRajan-dev

**Pull request merged**
