### PR TITLE
Feat : Added Shadow To Each Card to Enhance its look

### PR DESCRIPTION
**Pull request by itsarraj**
Feat : Added Shadow To Each Card to Enhance its look

### CODE REVIEW

**Comment by Deva-1903** [comment]
@itsarraj  Upload a screenshot of your output, then double-check your PR it has 127 commits.

**Comment by JasonDsouza212** [comment]
The changes you made are huge. I think you should break down the problem and create a separate pull request for each bug or enhancement. Otherwise, there will be merge conflicts

**Comment by itsarraj** [comment]
I understand , currently travelling , will fix it soon

**Comment by JasonDsouza212** [comment]
> The changes you made are huge. I think you should break down the problem and create a separate pull request for each bug 
irst create an issue and then solve it by this when you address the issue during the pull request

Dear @itsarraj, instead of creating a pull request for all changes at once,I suggest  you breaking down to issues and creating separate  ones for each change. This way, it will be easier to evaluate and address the issues during the pull request, making it easier to resolve any potential merge conflicts.

**Pull request closed without merging**
