### PR TITLE
Added 4 Filters

### LINKED ISSUE #947: [Feat]: Add more filters
### What feature?

I have an idea to add more filters in the [filters.js](https://github.com/JasonDsouza212/free-hit/blob/main/src/utils/data/filters.js) file for better categorization of all the resources.
The filters i would like to add are:
<ul>
<li>Image Generation</li>
<li>Chatbots</li>
<li>Content Generation</li>
<li>Presentations</li>
<Prompts</li>
</ul>

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by inkerton**
## Related Issue

Closes #947 

## Description

Added more filters and will be adding 8 resources for each filter soon.
## Screenshots
image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@inkerton, we can only consider a category if there are 8 or more tools in it

**Comment by inkerton** [comment]
> @inkerton, we can only consider a category if there are 8 or more tools in it

I have the list. I'll make an issue for each category and submit PRs for all them.
Already generated one issue<b> #1227 </b>for image generation filter.

**Comment by inkerton** [comment]
> @inkerton, we can only consider a category if there are 8 or more tools in it

Generated another issue for <b>'chatbots' filter : #1228 </b>

**Comment by JasonDsouza212** [comment]
@inkerton, add them Along with the tools. Additionally, ensure that you add the categories in three different places.

**Pull request closed without merging**
