### PR TITLE
Added Few More Websites🔗

### PR DESCRIPTION
**Pull request by sushilpandeyy**
I added few more website specifically Pogolink, Notion and I Love PDF, please merge this commit and i will try to continuously contribute in this project.

### CODE REVIEW

**Comment by sushilpandeyy** [comment]
Please review this @JasonDsouza212

**Comment by JasonDsouza212** [comment]
Looks fine can you shorten the image links using bitly or any other websites

**Comment by priyankarpal** [comment]
here is a possible solution @JasonDsouza212 whenever we provide an image link; we don't need to shorten just drag & drop the image to the github issue and copy the generated `userimages. github...` link & paste it to the json file.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by sushilpandeyy** [comment]
Changed Url Length, please check @JasonDsouza212 & @priyankarpal

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by sushilpandeyy** [comment]
I want to contribute more could please guide me from where i can start, as i am not able to find issues which i can solve  @JasonDsouza212 & @priyankarpal

**Comment by priyankarpal** [comment]
> I want to contribute more could please guide me from where i can start, as i am not able to find issues which i can solve @JasonDsouza212 & @priyankarpal

You can add more websites, redesign website pages etc.

**Comment by sushilpandeyy** [comment]
@priyankarpal please merge these changes

**Comment by priyankarpal** [comment]
> @priyankarpal please merge these changes

@JasonDsouza212 will merge it soon

**Comment by priyankarpal** [comment]
@sushilpandeyy check this issue #45

**Comment by JasonDsouza212** [comment]
> @JasonDsouza212 in this way we can add images.

This is a good alternative, but Bitly offers a shorter URL by using its algorithm to shrink the original URL

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
