### PR TITLE
feat: feature added for start and end page arrow

### LINKED ISSUE #1138: Add arrows for first and last page
### What feature?

I have an idea of implementing two arrows which will directly take to first and last page in below section as it will be more user friendly.

### Add screenshots

Add screenshots
Screenshot (90)

### Code of Conduct

Please assign this issue to me under GSSOC'23
- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by I-shika**
## Related Issue

Closes #1138 

## Description

two arrows are added for directing directly to front and last page.

## Screenshots
Screenshot (99)

Screenshot (98)

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by JasonDsouza212** [comment]
Please add a screen recording of all media widths.

**Comment by I-shika** [comment]
I have resolved the error. Please review it.

**Comment by JasonDsouza212** [comment]
Pagination  is covering the whole application
Screenshot from 2023-07-05 20-00-55

**Comment by I-shika** [comment]
Changes completed. @JasonDsouza212 please review it.

**Comment by JasonDsouza212** [comment]
Send a screen recording in all widths

**Comment by I-shika** [comment]
[Screen Recording - Made with FlexClip.webm](https://github.com/JasonDsouza212/free-hit/assets/100770197/5c2012c9-5ede-4329-a0ca-242862c9b06c)

Please review this

**Comment by I-shika** [comment]
@JasonDsouza212  please review this

**Comment by JasonDsouza212** [comment]
@I-shika, it still looks cluttered. One possible solution is to make it appear as a button with a black background and white text, giving it a cleaner look. Additionally, consider removing the bottom "Next" and "Previous" buttons since the newly added feature performs the same functionality.

**Comment by I-shika** [comment]
[screen-capture.webm](https://github.com/JasonDsouza212/free-hit/assets/100770197/80520db6-8134-4fc6-ba83-81774c1216b7)

Screen recording 
@JasonDsouza212 please review this.

**Comment by JasonDsouza212** [comment]
@I-shika, the black background you added doesn't match the application's black color. Please make sure it matches. Additionally, we don't need the ">>" arrow in the top navigation. Instead, add it at the bottom. Also, ensure that the buttons have the same width and height.

**Comment by I-shika** [comment]
I have done the required changes please review it. @JasonDsouza212 
Screenshot (128)
Screenshot (127)

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
