### PR TITLE
feat : Zoho site added #958

### LINKED ISSUE #958: [Feat]:  adding zoho site
### What feature?

Zoho Sites is a website builder and hosting platform provided by Zoho Corporation. It allows individuals and businesses to create and manage professional websites without requiring extensive technical knowledge or coding skills.

Link - https://www.zoho.com/sites/

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mandliyarajendra11**
## Related Issue

Closes #958 

## Description

Zoho Sites is a website builder and hosting platform provided by Zoho Corporation. It allows individuals and businesses to create and manage professional websites without requiring extensive technical knowledge or coding skills.

## Checklist

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by JasonDsouza212** [comment]
I dont think ZOHO is free

**Comment by mandliyarajendra11** [comment]
> I dont think ZOHO is free

15 days free trial

**Comment by JasonDsouza212** [comment]
We need something that can be freely used

**Pull request closed without merging**
