### PR TITLE
fix: Need to build Light mode of navbar #1331

### LINKED ISSUE #1331: [style]: Need to build Light mode of navbar
### What's the style idea?

We need to improve  
The side Navbar of the product Free-Hit has a dark mode view but not a light mode.
So, the users who want light mode as default we must show navbar in light mode

Please assign me his task under GSSOC'23

### Add screenshots

Add screenshots
image
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by soubhik-111**
## Related Issue
 Need to build Light mode of navbar #1331
Closes #1331

## Description
Light mode Navbar

## Screenshots
image

## Checklist

- [X] My code adheres to the established style guidelines of the project.
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@soubhik-111, it would be good if the navbar in light mode is dark, and you can try implementing the light sidebar in dark mode. If it looks good, we can merge it.

**Comment by soubhik-111** [comment]
Are you recommending for alternative mode with respect to the main site.

**Comment by JasonDsouza212** [comment]
I mean the dark sidebar looks good with the light mode, so we can try implementing a light mode sidebar in dark mode. If it looks good, then we can go with that design.

**Comment by soubhik-111** [comment]
Check it now.

**Comment by soubhik-111** [comment]
@JasonDsouza212 
Kindly merge it.

**Pull request closed without merging**
