### PR TITLE
feat: freeCodeCamp

### LINKED ISSUE #886: [Feat]: Add freeCodeCamp Website for Better, Faster and Easier Code Practicing in Trending Technologies
### Feature Description:
- **` Add freeCodeCamp Website for Better Faster Easier Code Practicing in Trending Technologies`**

### Add screenshots

Add screenshots:
freehit-6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Related Issue

Closes #886 

## Description

- **Add freeCodeCamp Website in product.json File for Learning Web Development with Huge Collection of Challenges**

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@NarendraKoya999, please revert all the changes and only add FreeCodeCamp. You can review all the changes you made in the "Files Changed" section, so take a look and create the pull request correctly. Make sure not to add anything more or less than what is necessary in the PR.

**Comment by NarendraKoya999** [comment]
> 

Okay @JasonDsouza212 .Sorry for making Big Mistake. I have Fully Trapped in JSON Checker. I did not Repeat these above Guidelines

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 , you can either edit your existing code directly or start from scratch.

**Comment by NarendraKoya999** [comment]
>
@JasonDsouza212 . I can start Edit Small things with Existing Code Whatever Before Already Raised and Closed That My PR's Recently.

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 ,still not satisfied with your PR

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 ,still not satisfied with your PR

I think You Tell Needed Small Changes in this freeCodeCamp related PR ?. Please elaborate What the Issue?

**Comment by JasonDsouza212** [comment]
This Is how the PR should look like
Screenshot_20230704-132642

This is how your PR looks,Your PR is changing unnecessary lines , and also deletes many tools too
Screenshot_20230704-132715

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 ,still not satisfied with your PR

Ok Got It @JasonDsouza212

**Comment by NarendraKoya999** [comment]
Hi @JasonDsouza212 . I will start Freshly. Because of All Unnecessary Changes made with Individual Commits. So, I can revert Back with Changed code along with related Commits . It's Huge Work. I can Proceed Create a New PR Till Now.

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 OK

**Comment by NarendraKoya999** [comment]
Hi @JasonDsouza212 . I have Some Doubt.  In my Codebase of freehit Project Directory, Shown Whatever closed PR and That all My Pushed Changes Code Appeared. How Should I go Further Proceed Include this Closed freeCodeCamp Object shows in DB JSON File Also. How to Move It for Create a New PR?

**Comment by NarendraKoya999** [comment]
Hi @JasonDsouza212 . Please Help. I have Less Knowledge on Git and GitHub.

**Pull request closed without merging**
