### PR TITLE
 modified scroll bar #1587

### PR DESCRIPTION
**Pull request by piyushkhurana2019**
Issue #1587 resolved

## Description

Added stylish scrollbar which enhanced the beauty of the website

## Screenshots

Screenshot 2023-08-10 at 12 08 18 AM

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Attach a screen recording that demonstrates the changes you made to the code, showing how it affects the application across all media widths.

**Comment by piyushkhurana2019** [comment]
Kindly have look sir, responsiveness of the website is maintained.


https://github.com/JasonDsouza212/free-hit/assets/96003210/ef260baf-1463-438d-a435-3ddf00dd3ffe

**Comment by piyushkhurana2019** [comment]
@JasonDsouza212 , Sir please kindly merge my pull request, The GSSOC deadline is approaching.

**Comment by JasonDsouza212** [comment]
@piyushkhurana2019, The old design aligns better with the theme, so we cannot proceed with the new design. However, I noticed a bug in the application: the alignment of the dark mode/light mode button and the back-to-top button in tab mode is not properly aligned. Could you please take care of this issue specifically in those widths? Mobile and desktop widths are aligned correctly.

**Comment by piyushkhurana2019** [comment]
Sure Sir kindly have a look at PR #1595

**Pull request closed without merging**
