### PR TITLE
fix: added the linkedin button in about sidebar #1559

### LINKED ISSUE #1559: [Feat]: Add a LinkedIn share button in the About page
### `Under GSSOC'23`

- I have an idea of adding a LinkedIn share button in the sidebar of the About page. 
- The LinkedIn Share Button is the easiest way to remind and encourage users to post and share your website on LinkedIn.

### Add screenshots

Example:
linkedin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tanujbordikar**
## Related Issue

Closes #1559 

### `Under GSSOC'23`

- Added the LinkedIn share button in the sidebar of the About section.
- After clicking it will redirect to the linkedin sharing page where you can share it in a DM or as a post.

## Screenshots
linkedin-new

**Video:**

https://github.com/JasonDsouza212/free-hit/assets/91179998/138f0b3b-83ab-4755-9e09-577bef87fb70

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by tanujbordikar** [comment]
okay sure

**Comment by tanujbordikar** [comment]
hey @JasonDsouza212 , is there any other thing you need to verify the site's functioning?

**Comment by JasonDsouza212** [comment]
@tanujbordikar, it's not currently copying the message to LinkedIn. The intended functionality is that when the button is clicked, it should redirect to LinkedIn with the provided data [message]. This would allow the user to simply click the button to post it without any extra effort, similar to how the Twitter button works.

**Comment by tanujbordikar** [comment]
I searched it and got to know that linkedin has removed the feature of that thing a long back ago.

**Comment by JasonDsouza212** [comment]
@tanujbordikar, that was actually the reason we didn't add it back then. I thought you had a solution for it, if we can't achieve that then In that case, we can't go ahead and proceed with the PR.

**Comment by tanujbordikar** [comment]
hey @JasonDsouza212 , don't close this pr! Give me some time so that I will find a way to tackle that problem!

**Comment by JasonDsouza212** [comment]
@tanujbordikar sure take your time

**Comment by JasonDsouza212** [comment]
@tanujbordikar Shall I close the issue

**Comment by tanujbordikar** [comment]
@JasonDsouza212 yeah you can, I have tried it and was unable to find the solution.

**Pull request closed without merging**
