### PR TITLE
Updated footer

### PR DESCRIPTION
**Pull request by Esha-01**
## Related Issue

Closes #issue_number

## Checklist 

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] My changes have not introduced any new warnings.
- [ ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@Esha-01 the footer looks small as well as there is a extra white space

**Comment by VenomFate-619** [comment]
add issue number in pr description

**Comment by Esha-01** [comment]
issue id is #381

**Comment by JasonDsouza212** [comment]
@Esha-01 , What does the text area serve

**Comment by JasonDsouza212** [comment]
As this is duplicate PR Ill be closing it

**Pull request closed without merging**
