### PR TITLE
fix: Improvement in Contributors Section

### LINKED ISSUE #599: [style]: Improve UI of contributors page
### What's the style idea?

Improving UI of contributors page, to add animations and hover effect. Please assign me this issue under GSSOC'23. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Closes #599 

In the contributors section of the website, contributors name and their commits have been added and a card has been created.

## Screenshots

image

image

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Vidip-Ghosh** [comment]
@JasonDsouza212 Can you please review this PR?

**Comment by Vidip-Ghosh** [comment]
@JasonDsouza212 please review this PR

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-07-09 at 20 15 53
Screenshot 2023-07-09 at 20 15 05
Latest changes being made.

**Comment by Vidip-Ghosh** [comment]
@JasonDsouza212 Please review the latest changes

**Comment by JasonDsouza212** [comment]
Screenshot from 2023-07-11 16-37-32
Screenshot from 2023-07-11 16-37-23
You can observe the difference in the logo and the navbar's bottom border. Can you correct that? Alternatively, one suggestion is to synchronize your branch with the latest code and only modify the code for the contributor's page. Leave everything else the same as Free-hits. I believe this approach will resolve any unnecessary changes.

**Comment by JasonDsouza212** [comment]
Also, please make the border of the contributor card match the white color theme of Free-hit.

**Comment by JasonDsouza212** [comment]
rest everything is fine

**Comment by Vidip-Ghosh** [comment]
Sure I will correct those.

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-07-11 at 18 37 54
Done with the changes

**Pull request closed without merging**
