### PR TITLE
chore: Added Prettier #899

### LINKED ISSUE #899: [Feat]: Add Prettier Extension
### What feature?

I would like to add Prettier extension 
Prettier is an extension or a tool that helps with code formatting. It provides a code formatter that can be integrated into your code editor or build process. Prettier supports various programming languages, including HTML, CSS, and JavaScript, and helps enforce consistent code style and formatting across your project. By using Prettier, you can automate the process of formatting your code, making it easier to maintain a consistent and readable codebase. We can use this extension on our code editor platforms.

### Add screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Parul1606**
## Related Issue

Closes #899 

## Description

I have added prettier extension which can be integrated to code editors and supports various programming languages.

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by Parul1606** [comment]
I'm a contributor to both gssoc and ssoc, can I be assigned both labels?

**Comment by JasonDsouza212** [comment]
@Parul1606 , Your PR removes an tool , add that back

**Comment by Parul1606** [comment]
@JasonDsouza212 is it fine now?

**Comment by JasonDsouza212** [comment]
Screenshot from 2023-07-08 19-33-22
The issue is intended to add only one tool, but your PR is removing two tools.

**Pull request closed without merging**
