### PR TITLE
A default picture must be present if the image is not rendered #178

### PR DESCRIPTION
**Pull request by aashay28**

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@aashay28  The changes you made are good, but I think the image we are displaying might not be a good choice as it is somewhat odd. So, to keep it simple, I suggest that we add another image 

You can add this for now : https://bit.ly/3n91Lj2

**Comment by JasonDsouza212** [comment]
And regarding the changes you made, how exactly will it work? When will it be triggered? I mean, 
- will it be if the image **URL is not reachable** 
- Or if the **URL does not exist in the database?** 
- Or will it output whichever **image is fetched faster**?

**Comment by aashay28** [comment]
> And regarding the changes you made, how exactly will it work? When will it be triggered? I mean,
> 
> * will it be if the image **URL is not reachable**
> * Or if the **URL does not exist in the database?**
> * Or will it output whichever **image is fetched faster**?

> It will triggered if the image url is not available.

**Comment by JasonDsouza212** [comment]
You can download it and then display it by putting the image in the 'images' directory.

**Comment by aashay28** [comment]
> You can download it and then display it by putting the image in the 'images' directory.

Please verify the same

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
thank you for your contribution @aashay28

**Pull request merged**
