### PR TITLE
feat: Created Browser Extention for to website

### LINKED ISSUE #1094: [Feat]: Browser extension of the website
### What feature?

This website can be extended to an browser extension and  there user can list the website he wants through a search bar

### Add screenshots

this is a sample view of the feature
image
user can select the desired type of the website he wants in the search section
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by VivekYadav105**
## [Feat]: Browser extension of the website #1094 

Closes #1094 

## Description
Browser extension feature of the website is added here.
It would be easy and convenient for the user to search the websites from the extension.

added a folder named extension with an html file `index.html`, a script file `script.js`, a CSS file `style.css` manifest file for the extension `manifest.json` and few other images relevant to the logo  

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by VivekYadav105** [comment]
yep changed the title to correct format

**Comment by JasonDsouza212** [comment]
@VivekYadav105, the idea is good. However, the back button is not working, and the search functionality is not accurate or correct. It also needs some styling. Additionally, you can increase the UI width and improve the styling as it appears congested.

**Comment by VivekYadav105** [comment]
I edited the design and fixed the input bug. This is how the new ui looks
image
this is the new UI and now user can see the details of the website only on clicking them
image
the top link button redirects to main website .

**Comment by VivekYadav105** [comment]
do you want me to change the font family?
I picked up this font from the main website some where but it is not appliied to the complete website

**Comment by JasonDsouza212** [comment]
Screenshot from 2023-07-04 09-54-01
When I search for the URL, I'm not getting any tools. Additionally, when I click on 'Visit Main Website,' it's not taking me there
Screenshot from 2023-07-04 09-55-11
And you can see that the description is being covered, so give it enough space. Additionally, if possible, you can also add a sidebar for categories.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
