### PR TITLE
docs: Updated main README.md

### LINKED ISSUE #1495: [Docs]: Improve README.md
### what's wrong in the documentation?

Adding the benefits of contributing in open source and how this project can be useful for everyone.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deepshikha2708**
## Related Issue

Closes #1495 

## Description

Added the reason in readme as to why to contribute in open source.

## Checklist

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] My changes have not introduced any new warnings.
- [ ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@deepshikha2708, you need to explain more about what contributors will gain from contributing. You should mention how they can showcase their contributions on their resumes, and it would be better to present the information in bullet points to keep them concise and easy to read.

**Comment by deepshikha2708** [comment]
@JasonDsouza212 made the changes as per the request. Kindly check it.

**Comment by JasonDsouza212** [comment]
@deepshikha2708, could you please add only the following information? You can make the key values bold and add some bullet points. Each point should be concise.
## 🌟 Benefits of Contributing to Open-Source

Contributing to open-source projects like Free-Hit has numerous benefits. It helps you:

- Give back to the community: By contributing, you help grow and improve the tools that you and many others use.
- Build your portfolio: Your contributions can serve as real-world examples of your work and make you stand out in the job market.
- Improve existing skills and learn new ones: Working on real-world projects gives you the chance to apply what you've learned and gain more knowledge along the way.
- Network with professionals: You get to connect and collaborate with professionals around the world, opening up potential job opportunities.

**Comment by deepshikha2708** [comment]
@JasonDsouza212 I added the resume point.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
