### PR TITLE
feat: add loader on Home page

### LINKED ISSUE #461: [Feat]: Adding Loader
### What feature?

We can show a loader to the user whenver the user changes the pages and when the website loads for the first time.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
fixes #461

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Can you add a video

**Comment by kailashchoudhary11** [comment]
> Can you add a video

https://www.loom.com/share/fa365d03b17143dd9e9fd91ed6c90b5f

**Comment by kailashchoudhary11** [comment]
@JasonDsouza212 I've added the video.

**Comment by VenomFate-619** [comment]
do not use a package for this, you can make a loader yourself also.
adding a package will increase the application bundle size.

**Comment by kailashchoudhary11** [comment]
> do not use a package for this, you can make a loader yourself also. adding a package will increase the application bundle size.

I've made the changes, kindly review

**Comment by JasonDsouza212** [comment]
can you add a screen video @kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
> can you add a screen video @kailashchoudhary11

Sure, here is the video.

https://www.loom.com/share/d1b9c61856064984b446243e7958ad1f

You can check it by clicking on Visit Preview. 
image

**Comment by JasonDsouza212** [comment]
Ok

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
