### PR TITLE
feat: Treehouse

### LINKED ISSUE #912: [Feat]: Add Treehouse Website for Learning Web Development
### Issue Description
- **`Add Treehouse for Learning Web Development Technologies`**

### Add screenshots

Add screenshots
freehit-15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Related Issue

Closes #912 

## Description

- **Update Treehouse Object in product.json File for Learning Web Development**
## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@NarendraKoya999, Universe.io is already in the database, and currently, we don't need Naukri. Therefore, please remove both tools. The issue specifies only adding the Treehouse tool, so please only include that one in your PR

**Comment by NarendraKoya999** [comment]
I can Directly change these things in Files Changed Section? @JasonDsouza212

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 yes you can do it

**Comment by NarendraKoya999** [comment]
I have changed all above you are Requested Things. Please Check @JasonDsouza212

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 , I guess now u know how to do it

**Comment by NarendraKoya999** [comment]
Yes. @JasonDsouza212 . I have Full Clarity on How to handle Forked repository with Issues and PR's

**Pull request merged**
