### PR TITLE
Adding of Products in Products.json

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
I have added the Chaijs, Mochajs and Chai matchers in the products.json with shorten their link and also kept the description also short

@JasonDsouza212

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
can you shorten the description length of **mocha js** and **chaijs**. The description should have max 10-12 words in it

**Comment by Bharadwajshivam28** [comment]
> can you shorten the description length of **mocha js** and **chaijs**. The description should have max 10-12 words in it

Okay

**Comment by JasonDsouza212** [comment]
@Bharadwajshivam28 this branch has conflicts do resolve it

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by JasonDsouza212** [comment]
> can you shorten the description length of **mocha js** and **chaijs**. The description should have max 10-12 words in it

@Bharadwajshivam28 you didn't complete this

**Comment by Bharadwajshivam28** [comment]
okay i will complete this one

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 crating a fresh pr by closing this one

**Pull request closed without merging**
