### PR TITLE
Search Area Design Improvement

### LINKED ISSUE #817: [Feat]: Search Area Design Improvement
### What feature?

The current design is nice but it can be improved by working on the styling of this section. By adjusting some of the styling features of this section, I can make it look even better.

### Add screenshots

**Current Design**
freehit (3)

**Expected Updated Design**
freehit (2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iamRabia-N**
## Related Issue
Closes #817

## Description
This PR contains the updated code for the "Search Area" design improvement.

## Screenshots
freehit (2)

## Checklist
- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Can you add screen recordings in all media widths, please?

**Comment by iamRabia-N** [comment]
@JasonDsouza212 
[Output sample](https://drive.google.com/file/d/1YwbvYR9Iyx6HieyCUQ9J6EjVC4l65--m/view?usp=sharing)

**Comment by VenomFate-619** [comment]
image

fix the alignment of the icon

**Comment by iamRabia-N** [comment]
> image
> 
> fix the alignment of the icon

@JasonDsouza212 Done

**Comment by iamRabia-N** [comment]
@JasonDsouza212

**Comment by VenomFate-619** [comment]
> > image
> > fix the alignment of the icon
> 
> @JasonDsouza212 Done

still it is not fine , 
try to fit that search icon inside the input bar

**Comment by iamRabia-N** [comment]
ss
It's good on my end. The latest commit has brought these changes.

**Comment by iamRabia-N** [comment]
@

> ss It's good on my end. The latest commit has brought these changes.

@JasonDsouza212

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
