### PR TITLE
Added some remote jobs as flexjobs,insidea,findasync,crossver to remote work.

### PR DESCRIPTION
**Pull request by kumar007ambi**
This is the Issue Number  #433
I have added the resources as contribution.md file recommended.

### CODE REVIEW

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
The Json structure should look like this
  {
    "productName": "Animoto",
    "category": "AI",
    "image": "https://bit.ly/3WSfus6",
    "link": "https://animoto.com/",
    "description": "Create videos that engage and impress. Animoto's drag-and-drop editing tools and visual effects make it easy. No training or experience necessary"
  },

**Comment by JasonDsouza212** [comment]
@kumar007ambi resolve the conflicts

**Comment by kumar007ambi** [comment]
@JasonDsouza212 I have resolved the conflicts

**Comment by JasonDsouza212** [comment]
@kumar007ambi, you have removed Zarla, Unblast, and Zety from the database. Please add them back in order to get your PR merged.

**Comment by JasonDsouza212** [comment]
@kumar007ambi, also go through the documentation as there are some rules that need to be followed in order to get the PR merged. Because I noticed that there is no issue number linked with the PR.

**Comment by JasonDsouza212** [comment]
@kumar007ambi are you done wit your changes

**Comment by kumar007ambi** [comment]
@JasonDsouza212 Yes

**Comment by kumar007ambi** [comment]
@JasonDsouza212 I have done with the changes

**Comment by JasonDsouza212** [comment]
**Make only the changes you have specified. Your pull request contains many unnecessary changes.**
image

**Comment by kumar007ambi** [comment]
How can I revert that changes

**Pull request closed without merging**
