### PR TITLE
feat: migrated to Tailwind CSS 🤕

### PR DESCRIPTION
**Pull request by priyankarpal**
## Done 
- redesigned header, footer, card
- changed the bg colour
- deleted extra code
- upgraded all dependencies
- changed default font to `JetBrains Mono`
- responsive design

https://user-images.githubusercontent.com/88102392/230708709-0ac0b7fd-9c4d-4d5e-a7c4-fa646be11533.mp4

### CODE REVIEW

**Comment by priyankarpal** [comment]
@JasonDsouza212 please review it.

**Comment by JasonDsouza212** [comment]
- @priyankarpal I believe there are several areas that require improvement. Firstly, the buttons are not of the same size. 
- Additionally, the color scheme is too bright and not a good choice. 
- The cards are also too big; I recommend having 5 cards per row. 
- The mobile view is not satisfactory either.
- Could you please explain why there were changes in the image links in the products.json file?

**Comment by priyankarpal** [comment]
> * @priyankarpal I believe there are several areas that require improvement. Firstly, the buttons are not of the same size.
> * Additionally, the color scheme is too bright and not a good choice.
> * The cards are also too big; I recommend having 5 cards per row.
> * The mobile view is not satisfactory either.
> * Could you please explain why there were changes in the image links in the products.json file?

ok first of all I'm using Brave browser here all things are ok but in the json file, I changed it because some images are not loading properly

**Comment by JasonDsouza212** [comment]
I should think about the color scheme.if you have anything in mind you can say it

**Comment by priyankarpal** [comment]
> I should think about the color scheme.if you have anything in mind you can say it

Okay, I will send it if I get it.

**Comment by JasonDsouza212** [comment]
Okay

**Comment by bharathkalyans** [comment]
I see this issue has been closed but I think it has not been deployed right? @JasonDsouza212

**Pull request closed without merging**
