### PR TITLE
Added the sorting message and is working perfect

### PR DESCRIPTION
**Pull request by Gautam-666**

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Is this the same code as the sort branch?? or did you make any changes

**Comment by Gautam-666** [comment]
I have changed some code patterns . Also in the  header file  the button was displaying ascending and descending vice-versa. They weren't in sink.

**Comment by JasonDsouza212** [comment]
can you add some screen recordings and screenshots

**Comment by Gautam-666** [comment]
What do you need in recording and screenshots...so that I can take them perfectly?

**Comment by JasonDsouza212** [comment]
add both and also include screenshots of the mobile view

**Comment by JasonDsouza212** [comment]
add both and also include screenshots of the mobile view

**Comment by priyankarpal** [comment]
@Gautam-666 I would like to say that add a default inbuilt function instead of giving a button.

What about you @JasonDsouza212 ?

image

**Comment by priyankarpal** [comment]
one suggestion @Gautam-666 whenever you create a PR/issue please add a **description** & **screenshots(if needed)**. It helps maintainers to understand the changes they have made.

**Comment by Gautam-666** [comment]
@priyankarpal i understood your point ....will remember to add screenshot from next time.

**Comment by Gautam-666** [comment]
@JasonDsouza212 I won't be able to work on the project this week. I have  examination and some prior commitment. If you can wait I will sort it after that . Otherwise you can alot it to someone else.

**Comment by priyankarpal** [comment]
> @priyankarpal The project is always sorted in ascending order, Yup I think descending is not needed as of now

okkk

**Comment by Gautam-666** [comment]
So maybe you can close the pull req...!

**Comment by JasonDsouza212** [comment]
yup go ahead and close it @Gautam-666

**Comment by Gautam-666** [comment]
Should I leave the branch or delete it as well??

**Pull request closed without merging**
