### PR TITLE
Feat : Added Shadow To Each Card to Enhance its look , Containter shadow feature : 

### PR DESCRIPTION
**Pull request by itsarraj**
Screenshot from 2023-03-30 04-23-50

### CODE REVIEW

**Comment by itsarraj** [comment]
@JasonDsouza212 Check Bro

**Comment by itsarraj** [comment]
Screenshot from 2023-03-30 04-23-50

**Comment by itsarraj** [comment]
Screenshot from 2023-03-30 23-01-17

**Comment by priyankarpal** [comment]
This branch has a conflicts error. Please resolve it.

**Pull request closed without merging**
