### PR TITLE
feat: implement dedicated share model component for sharing links  🚀🔥 

### LINKED ISSUE #1558: feat: implement dedicated share model feature for sharing resources 💡✨
## Current Situation
- The Free Hit repository serves as a valuable resource for discovering and sharing free tools that cater to various needs. However, the current implementation lacks a dedicated share model component for sharing links to these free tools. 
- Presently, the link is merely copied to the clipboard, and a simple `alert()` function is used to inform users about the copied link.

## Proposed Solution
- To enhance the user experience and make it easier for users to copy and share the links of the free tools they find, I propose implementing a share model component with a copy link feature. 
- This component will allow users to view the link and easily copy it to their clipboard for sharing.

## Features of the Share Model Component:
1. **Copy Link Feature:** The share model component will prominently display the link to the free tool. Additionally, it will include a button or icon that users can click to copy the link to their clipboard.

2. **User-Friendly Interface:** The share model component should have a clean and user-friendly interface that prominently displays the link and the copy link button. It should be intuitive for users to understand and use.

3. **Responsive Design:** The share model component should be designed to work seamlessly on various devices and screen sizes, ensuring a consistent experience for all users.

4. **Accessibility:** The component should be accessible, ensuring that users with disabilities can use the copy link feature without any barriers.

5. **Visual Feedback:** The component should provide visual feedback when the link is successfully copied to the clipboard, such as displaying a tooltip or a notification to inform the user.

## Expected Outcome
- By implementing the share model component with a copy link feature, Free Hit repository users will have a more convenient and efficient way to copy and share the links of the free tools they discover. 
- This enhancement will improve the user experience and encourage users to share valuable resources, contributing to the community's growth and engagement.

## Screenshot (Example Share Model)
image

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Related Issue

Closes #1558 

## Description

- Enhanced the user experience by adding a new feature that enables users to copy shareable links for products in both the GridView and ListView components.
- Implemented a share button behavior that copies the link to the clipboard when clicked.
- Introduced user feedback for successful link copying by displaying a "Copied" tooltip on the Share Model component after clicking the copy icon.
- Integrated an accessible and adaptable Share Model component for presenting the copied link in a visually appealing manner.
- The Share Model component now seamlessly adapts to the dark and light modes of the website, ensuring optimal visibility and experience for users.
- This change significantly improves the user experience by streamlining link sharing and providing a user-friendly interface for link presentation.

## Demonstrating Video

https://github.com/JasonDsouza212/free-hit/assets/92252895/02c4da14-09bb-4a3a-b371-14e89f00dc9b

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Exciting update @JasonDsouza212, @VenomFate-619!! 

Implemented a seamless Share Model component enabling users to swiftly copy links, Dark/light mode adaptation included. 

Please make sure to review this PR ⭐

**Comment by JasonDsouza212** [comment]
@0xabdulkhalid can you also add the video of it in mobile view

**Comment by 0xabdulkhalid** [comment]
image

@JasonDsouza212, For mobile the sharing component will use Web Share API.

If it fails it will fallback and uses the dedicated share model component.

**Comment by 0xabdulkhalid** [comment]
<p>

## $\textcolor{yellow}{\textsf{If the Mobile device didn't have support for}}$
## $\textcolor{yellow}{\textsf{Web Share API then it will look like this}}$
## $\textcolor{yellow}{\textsf{for those devices.}}$

</p>

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
