### PR TITLE
 content inside cards centered

### PR DESCRIPTION
**Pull request by rahulrana701**
I have made the changes , I have aligned the content inside the cards properly
Screenshot 2023-06-03 155338

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
can you also add a large title card's  screenshot and also resolve the conflicts

**Comment by rahulrana701** [comment]
hi @JasonDsouza212 I can't understand properly what do you mean by large title card's screenshot , can you please explain in brief

**Comment by JasonDsouza212** [comment]
Screenshot from 2023-06-03 23-20-56
can you add this tools screen shot

**Comment by rahulrana701** [comment]
> Screenshot from 2023-06-03 23-20-56 can you add this tools screen shot
Screenshot 2023-06-03 232219

here it is

**Comment by rahulrana701** [comment]
Hi @JasonDsouza212 do I have to make some changes or it is ok...

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
This branch has conflicts , resolve it @rahulrana701

**Comment by rahulrana701** [comment]
> This branch has conflicts, resolve them @rahulrana701

how can I do that do I have to push my changes or my pr in the main branch ?? Can you please help ??

**Pull request closed without merging**
