### PR TITLE
chore: Added Enhancecv #851

### LINKED ISSUE #851: [Feat]: Online Resume Builder
### What feature?

I would like to add Enhancecv - an Online Resume Builder
EnhanceCV is an online platform designed to assist individuals in crafting compelling resumes and CVs. It provides a range of tools, templates, and features to enhance the presentation of skills and experiences, enabling users to create professional and impactful job application documents.

### Add screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Parul1606**
## Related Issue

Closes #851 

## Description

I have added the resume builder tool - Enhancecv.

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by Parul1606** [comment]
Hello @JasonDsouza212 @VenomFate-619  my gssoc and level labels are assigned b'coz of this i havent got any scored what to do now? please help me out..

**Comment by Parul1606** [comment]
Thank you so much!

**Comment by VenomFate-619** [comment]
we need to add the gssco23 tag then it will be counted.
do remember to tell to that you are working under the gssoc23

**Comment by Parul1606** [comment]
Yeah sure, and I'm also a SSOC contributor. So for that what should I do as this project is listed there too @VenomFate-619 @JasonDsouza212

**Pull request merged**
