### PR TITLE
fix: Update Footer of the website in the list view #826

### PR DESCRIPTION
**Pull request by lakshmishreea122003**
## Related Issue

Closes https://github.com/JasonDsouza212/free-hit/issues/826#issuecomment-1606217204

## Description

When there is limited content displayed in the search results on my React website, such as only one item, the footer is raised, resulting in empty space below it. I want to keep the footer in its place consistently regardless of the content displayed.

## Checklist

- [X ] My code adheres to the established style guidelines of the project.
- [X ] I have included comments in areas that may be difficult to understand.
- [X ] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by lakshmishreea122003** [comment]
the screenshots are provided in [closed PR](https://github.com/JasonDsouza212/free-hit/pull/827)

**Comment by lakshmishreea122003** [comment]
How am I supposed to solve the problem due to the  PR title checker? Please let me know

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by JasonDsouza212** [comment]
Add a screen recording in all media widths

**Comment by lakshmishreea122003** [comment]
screen recording in all media widths

https://github.com/JasonDsouza212/free-hit/assets/117621286/4ed9cc99-0350-4a7d-9e9b-1542cab277f8

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003 resolve the conflicts

**Comment by JasonDsouza212** [comment]
Also, this feature should be applicable on all pages even in bookmarks

**Comment by lakshmishreea122003** [comment]
The bookmarks page has only a grid view. Thus it is consistent with the grid view on other pages like on the home page. This PR is about Updating the footer in the ListView when a single item is displayed on the screen

**Comment by lakshmishreea122003** [comment]
I am unable to figure out how to resolve the conflicts. Can you please guide me on that? Do let me know what to do.

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003, your fork is not synchronized with the latest code. Please sync it with the latest code, which may result in merge conflicts. Compare the conflicts and remove any unnecessary code that you don't need so that your code runs correctly without disrupting the Free-Hit code base.

**Pull request closed without merging**
