### PR TITLE
Added separate About tab in navbar.

### PR DESCRIPTION
**Pull request by Mayuresh-22**
### About this PR :
Added a separate tab for the About page in the navbar which was requested by others earlier. I have added an About tab in the navbar without any style issues, this about tab will be shown on both the Home page and the Bookmark page (No need to be shown on the About page itself). And as there is a separate tab for About now the site logo points to the Home page.

### Demo : 
ezgif com-video-to-gif

I hope this new addition will add more convenience to the users.
Thank You...

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
You have removed the redirection to the "about" page when the logo is clicked. Please revert that change.

**Comment by Mayuresh-22** [comment]
Okay 👍 I'll do it

**Comment by JasonDsouza212** [comment]
Just add the "About" button to the navbar, and keep everything else the same.

**Comment by Mayuresh-22** [comment]
> Just add the "About" button to the navbar, and keep everything else the same.

The requested changes are done have a look.

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
@Mayuresh-22 , looks perfect

**Comment by Mayuresh-22** [comment]
> @Mayuresh-22 , looks perfect

Thank You 🤗

**Pull request merged**
