### PR TITLE
Magic Eraser added to Free-Hit issue #528 GSSOC 2k23

### LINKED ISSUE #528: [Feat]: Add a new graphics designing tool
### What feature?

I have an idea  to add magic eraser which is powerful graphics designing tool which allows designers to remove unwanted elements in an image without messing with remaining part of the image.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by codin-AWMKAR**
## Related Issue

Closes #528 

## Description

Magic Eraser added to Free-Hit

## Screenshots

Screenshot 2023-06-08 205810g

## Checklist 

- [x ] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by codin-AWMKAR** [comment]
@JasonDsouza212 kindly review

**Comment by JasonDsouza212** [comment]
@codin-AWMKAR, there are certain rules that certainly need to be followed. Please refer to the README.md once and make the changes accordingly.

**Comment by codin-AWMKAR** [comment]
Oh sorry the word limit right? On it

**Comment by JasonDsouza212** [comment]
@codin-AWMKAR and also the tool should be added at the last

**Review by JasonDsouza212 — APPROVED** [review]

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
