### PR TITLE
feat: select multiple filters

### LINKED ISSUE #378: [Feat]: Select multiple filters at a time
### What feature?

We can allow the users to select multiple filters at a time.
As of now, the user can select any one of the available filters.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
fixes #378 
The users can now select multiple filters at a time.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The functionality is good, but the approach is not proper. Here's a suggestion: if the user presses Ctrl + [clicks on the category], it should select multiple filters. Otherwise, it should only filter one. This can be a useful feature. Additionally, please note that you have removed the icons, but we need those icons as well.

**Comment by kailashchoudhary11** [comment]
> The functionality is good, but the approach is not proper. Here's a suggestion: if the user presses Ctrl + [clicks on the category], it should select multiple filters. Otherwise, it should only filter one. This can be a useful feature. Additionally, please note that you have removed the icons, but we need those icons as well.

Actually if the user clicks on the filter button once the filter will get selected and if the user clicks on that filter button again it will be removed. So the user can select only one filter in this way. Also, not everyone knows that they can select multiple filter by using ctrl + click so it will degrade the user experience?

**Comment by kailashchoudhary11** [comment]
> The functionality is good, but the approach is not proper. Here's a suggestion: if the user presses Ctrl + [clicks on the category], it should select multiple filters. Otherwise, it should only filter one. This can be a useful feature. Additionally, please note that you have removed the icons, but we need those icons as well.

Which icons did I remove?

**Comment by JasonDsouza212** [comment]
Sorry , It was a mistake

**Comment by kailashchoudhary11** [comment]
> Sorry , It was a mistake

@JasonDsouza212 I've made the necessary changes as suggested.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
