### PR TITLE
chore: Added GoTranscript #864

### LINKED ISSUE #864: [Feat]: Add GoTranscript tool
### What feature?

I would like to add GoTranscript which gives Best Audio & video transcription services.
Gotranscript is a speech-to-text transcription service that converts audio and video files into written text. It utilizes a combination of automated algorithms and human transcribers to deliver accurate and efficient transcriptions. Users can upload their files, specify formatting preferences, and receive the transcriptions with quick turnaround times.

### Add screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Parul1606**
## Related Issue

Closes #864 

## Description

I have added the Gotranscript tool in db in tools category.

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by Parul1606** [comment]
Hello @JasonDsouza212 @VenomFate-619 my gssoc and level labels are assigned b'coz of this i havent got any scored what to do now? please help me out..

**Comment by Parul1606** [comment]
Please Please add my GSSOC labels @JasonDsouza212 @VenomFate-619

**Comment by JasonDsouza212** [comment]
@Parul1606 Sorry we have stopped giving points for tool addition

**Comment by Parul1606** [comment]
But the work has been done a week ago. Please give points on the work I
have done before, 4 PR's haven't been assigned labels till today. I have
requested on the PR at that time only and till date I didn't receive any
response. I hope you understand and assign my labels. Please it's a request.

**Comment by JasonDsouza212** [comment]
Okay, I'll give you points for this PR only because I have seen you contributing frequently. However, I cannot give you any points starting from the next one because we announced it a week ago in our discussions as well as on our Discord channel.

**Pull request merged**
