### PR TITLE
Dark mode option added

### LINKED ISSUE #561: [Feat]: Dark mode
### What feature?

We can add a moon icon at the top right to indicate dark mode. Clicking it will invert the color scheme making it look dark instead of light. Please assign me this issue.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kaashikaagrawal**
## Related Issue

Closes #561 

## Description

I have added a dark mode toggle option. This is a moon icon placed with the grid view and list view buttons. Clicking on it allows the page's css to change and adopt a dark theme.

## Screenshots

image

image

image

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Please add screen recordings of all pages and make sure to test them in various media widths as well.

**Comment by kaashikaagrawal** [comment]
I've checked on various devices and the dark mode seems to be working fine from my end.

**Comment by JasonDsouza212** [comment]
The dark and light modes are supposed to cover the entire application, and there are many changes that need to be made. For example, the navbar color and the About page background color are not changing, and the icon always remains the moon symbol. It should turn into a sun when we click on the moon, among many other necessary adjustments.

**Comment by JasonDsouza212** [comment]
That is why its a level 3 issue

**Comment by JasonDsouza212** [comment]
As the @kaashikaagrawal is not active , we will be closing this PR

**Pull request closed without merging**
