### PR TITLE
PR for Issue  : Grid view and list view #42

### PR DESCRIPTION
**Pull request by AbhayaShankar**
### There's a list of Enhancements I have made along with the Grid and List view which I am listing down below:

1. Grid View and List View - In this, I have made separate components for both `GridView.jsx` and `ListView.jsx` where `ListView.jsx` uses styles from `ListView.css` present in the styles folder.
Two icons added for Grid view and List view using react-icons. No extra packages installed.

https://github.com/JasonDsouza212/free-hit/assets/113185442/c6c46e8a-7b44-445b-9f5e-0bcec35f99cc

2. I have made a `FooterNew.jsx` component for a new Footer design. You can find that in the components folder, which uses styles from `FooterNew.css` defined in the styles folder. Nothing is overwritten, just displaying FooterNew instead of Footer.

image

image

This was what I designed for the FooterNew.If not good you can simply delete the `FooterNew.jsx` and the style `FooterNew.css` and enable the Footer component in App.js and you are good to go.

3. BackToTop design bit changed which not appears from top but from bottom... Previously when we scroll below 250px the button comes active and the button comes from top of the screen which looks bit poor rather than when it comes from bottom and looks good.

4. In Header component, I have switched the background color and color of Search component which looks better than prev one...

image

5. In the header and the menu bar also there was used `<a href="/"> </a>` tags which makes the page refresh. I have replaced them with `<Link to="/" >` tags from react-router-dom.

6. Images link added in `product.json` for Chajis and CleanVoice.

Thats's all.. Please go ahead and tell if anything feels out of place.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
I think you should create separate pull requests for each feature you have implemented so that I can review them individually and merge them.

**Comment by JasonDsouza212** [comment]
let the footer and search bar be the same @AbhayaShankar

**Comment by JasonDsouza212** [comment]
I think the placement of the grid view and list view buttons is not proper. We can discuss their placements and come to a better solution.By the way, those are some very good contributions that you have made @AbhayaShankar

**Comment by AbhayaShankar** [comment]
So @JasonDsouza212 For which features should I make the pull request for?
Like the grid view and List view is OK. But then for BackToTop also make a separate PR?

**Comment by AbhayaShankar** [comment]
## UPDATE PR 42

Updated the PR with all media queries responsive and working and no issues.

Here's screen rec. for the same - 

Media Responsive - 💯💯

https://github.com/JasonDsouza212/free-hit/assets/113185442/7a69951f-2fde-41f7-b256-478c29f6d348

BackToTop working just fine - 


https://github.com/JasonDsouza212/free-hit/assets/113185442/a484aeb1-1d3d-49a4-adba-82351517ce08

**Comment by JasonDsouza212** [comment]
The design still has some bugs in the mobile view. Additionally, please remove the newfooter code, as well as the related design folders and codes.
Screenshot from 2023-05-26 20-47-43

As you can see, the cards are not of the same length. Therefore, we can come up with another idea.

 The thing is, we can add collapsible elements when displaying the list view.By doing this, it will look uniform and neat on all screen sizes.

**Comment by AbhayaShankar** [comment]
Ok. Will remove the code for FooterNew and its corresponding codes.

As for the list view, Can design it to accordion if that works...

image

Similar to this...

**Comment by AbhayaShankar** [comment]
@Hi `@JasonDsouza212` I have successfully fixed the List view and designed a Accordion for that using **Chakra UI**. Have a look at the deployment if everything goes right, it could be merged.
I have checked for every media query and made sure everything works nice.

Also resolved all the merge conflicts. 🚀🔥

**Pull request merged**
