### PR TITLE
Fix issue 653

### LINKED ISSUE #653: [style]: Design the home page.
### What's the style idea?

Let's redesign this page to introduce "Free-Hit" and explain why we need it in our daily lives. After that, we can specify the features such as categories, how to use filters, selecting multiple filters, the search functionality, and other related aspects. Finally, we can highlight the most frequently used tools and present them at the end. If we structure the page in this way, it will be the best choice.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
Closes #653 

## Description

Responsive home page redesign.

## Screenshots

[Screencast from 21-06-23 12:43:40 AM IST.webm](https://github.com/JasonDsouza212/free-hit/assets/98320971/8a7b84da-2f1d-43e6-aab3-01723eaca90d)

## Checklist 

-  [x]  My code adheres to the established style guidelines of the project.
-  [x] I have included comments in areas that may be difficult to understand.
-  [x] My changes have not introduced any new warnings.
-  [x]  I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@ShreyaDhiman24, could you please revert the images back to their original state? Additionally, the paragraphs at the top have excessive padding, causing them not to fill the empty space adequately. Moreover, the font styling appears too basic. , let's limit the page to a maximum of eight tools and when clicked more it should navigate to home page

**Comment by ShreyaDhiman24** [comment]
> u please revert the images back to their original state

okay @JasonDsouza212 ! But, I didn't get what do you mean by revert the images back to their original state. Can you please explain it to me again please.

**Comment by JasonDsouza212** [comment]
@ShreyaDhiman24, the current application has an About page with attached images. I would like the same images to be included in your code. Additionally, I need the contributor section to be implemented as well. If you require more detailed information, I suggest contacting me through Discord, as it's difficult for me to respond adequately to numerous requests.

**Comment by ShreyaDhiman24** [comment]
okay

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
