### PR TITLE
Feat : Added Tools to databse 

### PR DESCRIPTION
**Pull request by itsarraj**
"productName": "FitText.js",
        "category": "tools",
        "image": "bit.ly/3M1UhIP",
        "link": "http://fittextjs.com/",
        "description": "FitText.js is a jQuery plug-in to make headline web type responsive to the design and the device"

### CODE REVIEW

**Comment by itsarraj** [comment]
Okay

**Comment by itsarraj** [comment]
Solved @priyankarpal

**Comment by JasonDsouza212** [comment]
I have left some comment on the description do check that out and resolve it

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request closed without merging**
