### PR TITLE
feat: Update_product.json-1418

### PR DESCRIPTION
**Pull request by lakshmishreea122003**
## Related Issue

Closes [#1418](https://github.com/JasonDsouza212/free-hit/issues/1418)

## Description

it helps Get more views on YouTube by researching keywords people are searching for.

## Checklist

- [X ] My code adheres to the established style guidelines of the project.
- [X ] I have included comments in areas that may be difficult to understand.
- [X ] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.

### CODE REVIEW

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003 attach the issue number the PR is supposed to close

**Comment by lakshmishreea122003** [comment]
I updated the PR name

**Comment by JasonDsouza212** [comment]
@lakshmishreea122003 attach the issue number

**Comment by lakshmishreea122003** [comment]
I did attach the issue number

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
