### PR TITLE
Balasarvan12 #603

### LINKED ISSUE #603: [Feat]: Add Freecodecamp to "Useful tools"
### What feature?

- FreeCodeCamp is an online learning platform that provides coding education and resources for free. 
- FreeCodeCamp's curriculum is divided into multiple certifications, starting with the Responsive Web Design Certification and progressing to more advanced topics such as Front End Development, Back End Development, Data Visualization, and Full Stack Development. Each certification requires completing a series of coding challenges, projects, and algorithmic exercises.
- For each certification, you need to build its 5 certification projects, and get all of the project tests to pass to be able to claim your certification.
- You can find more information about freecodecamp - https://www.freecodecamp.org/

### Add screenshots

Add screenshots
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by BALASARVAN12**
## Related Issue

Closes #603 

## Description

- freeCodeCamp is a non-profit organization that consists of an interactive learning web platform, an online community forum, chat rooms, online publications, and local organizations that intend to make learning web development accessible to anyone.
- Added info about freeCodeCamp in tools category of products.json

## Screenshots

image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by BALASARVAN12** [comment]
ok @JasonDsouza212 i will resolve conflicts

**Comment by BALASARVAN12** [comment]
@JasonDsouza212  again i should raise a pr

**Comment by BALASARVAN12** [comment]
@JasonDsouza212 i have reduced the description to 15 words.

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by BALASARVAN12** [comment]
@JasonDsouza212  merge my pull request

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
