### PR TITLE
chore: added UpGrad 

### LINKED ISSUE #1469: [Adding Tool]: Upgrad Learning Platform
### What tool are you adding and to what category?

- Upgrad is an online learning platform which includes wide range of courses from top universities
- It contains free courses as well as paid ones too

### Add Tool Link

Tool link - https://www.upgrad.com/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by siddarthdayala**
## Related Issue
#1469 

Closes #1469 

## Description

Just added a new learning platform called UpGrad in product,json file

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by siddarthdayala** [comment]
@JasonDsouza212 Could you please review this PR?

**Comment by siddarthdayala** [comment]
@JasonDsouza212 Upgrad provides many free courses too. As the matter of fact, other course platforms on Freehit do not provide free courses on the whole like Great Learning!

**Comment by JasonDsouza212** [comment]
@siddarthdayala if you find those platforms can you remove those ?? from the DB

**Comment by siddarthdayala** [comment]
> @siddarthdayala if you find those platforms can you remove those ?? from the DB

@JasonDsouza212 Sure!

**Comment by siddarthdayala** [comment]
@JasonDsouza212 removed a few with UpGrad tooo
You can close this PR as completed

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
