### PR TITLE
feat: Added the ability to search by category.

### LINKED ISSUE #130: Feature request: Add a search bar for both categories and tools
**Is your feature request related to a problem? Please describe.**

Finding a particular tool from the "all" tools category is a bit tedious as there are quite a number of tools there. Plus, maybe it's early because there not be many tools in some categories but soon there will be more tools and categories. Then searching can save the additional time to manually find it out. 

**Describe the solution you'd like**

So my suggestion is to add a search bar where we can search for both the tools and category.
Thank you.

### PR DESCRIPTION
**Pull request by Deva-1903**
Closes #130 

Updated search bar:
Screenshot (310)

### CODE REVIEW

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
good work @Deva-1903

**Comment by JasonDsouza212** [comment]
Always try to make necessary changes that solve the issue. 
All changes should not be in the same pull request, as some changes may not be recommended. 
For this, you need to change the code again, but this time, there won't be an issue. Try making a pull request for each individual change, from next time

**Comment by Deva-1903** [comment]
> Always try to make necessary changes that solve the issue. All changes should not be in the same pull request, as some changes may not be recommended. For this, you need to change the code again, but this time, there won't be an issue. Try making a pull request for each individual change, from next time

Which of the changes you believe I made here can be accomplished with another PR? @JasonDsouza212

**Comment by JasonDsouza212** [comment]
removing commas would have been another pr, Because they were intentionally placed

**Comment by JasonDsouza212** [comment]
Another question, can you explain me the functionality of the changes you made

**Comment by Deva-1903** [comment]
> removing commas would have been another pr, Because they were intentionally placed

It was not intentionally made. I use _**Prettier - Code formatter Extension**_ so it formatted the code automatically.

**Comment by Deva-1903** [comment]
> Another question, can you explain me the functionality of the changes you made
In the filterProducts function, I added a new line to search in category  **product.category.match(regex)**. Then in **const regex = new RegExp(searchTerm.trim(), 'gi')** added .trim() to remove spaces. Then changed placeholder=" Search for a tool or category..."
return (
        product.productName.match(regex) ||
        product.description.match(regex) ||
        product.category.match(regex)
      )

**Comment by JasonDsouza212** [comment]
Now leave about the pull request , Im not talking about it

**Comment by JasonDsouza212** [comment]
You added a new searching by entering the categories but If I type the category name I dont see the products being filterd

**Comment by JasonDsouza212** [comment]
Ho it's working good but the problem is we have the section name and the button values different, so it only filters when we enter the buttons value

**Comment by Deva-1903** [comment]
Yeah, for instance, for **ethical hacking** in category we named it only as "**ethical**", so if we type ethical, it displays everything related to ethical hacking, but if we type ethical hacking, nothing appears. We need to find a solution for this or we need to change the category name manually in data's.

**Comment by JasonDsouza212** [comment]
Ya, lets discuss that issue tomorrow and we are thinking of changing the UI entirely before that we need to solve this

**Pull request merged**
