### PR TITLE
feat: Added course platform in sidebar

### LINKED ISSUE #654: [Feat]: Add a Course section on Sidebar
Hey 👋, I am a Gssoc'23 contributor 

## What feature?

I have an idea to add a section of free course platform in the sidebar and want to add some free course platform like coursera, Edx, etc. 

### **Coursera -**
Coursera provides wide range of courses from top universities and institutions around the world. It has both free and paid courses, but you can access the course material for free. Financial aid option is available to access paid courses in free here. 

### **Edx -**
Edx offers free courses from renowned universities like Harvard, Boston, MIT etc. You can audit courses for free or choose to pay for a certificate upon completion.

### **CourseEra** 
image

### **Edx** 
image

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<br>
<br>

> **Kindly assign it to me under _GSSOC'23_** 
> **I will surely complete it ASAP** 

### Thank You

### PR DESCRIPTION
**Pull request by AKACHI-4**
## Related Issue

Closes #654 

## Description

Added a course section in sidebar having some links ( Actually 3 Links in first ) 

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The section should have at least have 8 tools

**Comment by AKACHI-4** [comment]
Hey I have added 8 tools for course section you can check it out now !! BTW I wanna ask about this PR Title Checker and Github actions How you are utilizing them in your project ??

**Comment by AKACHI-4** [comment]
## **Screenshot**

image

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
