### PR TITLE
Issue: #78 Use Vite Instead of CRA

### PR DESCRIPTION
**Pull request by dhawal-793**
Updated the project to use Vite Js, and removed some unwanted dependencies.

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉  Thanks for your contributions 🎉 ❤️

**Comment by priyankarpal** [comment]
one tip: whenever you add commits remember to add separate commits messages such as `docs: README.md file's typo fixed` etc. It helps us to maintain the code for a long time. But it's ok for now. ✌️

**Comment by JasonDsouza212** [comment]
I think this changes the steps for installing and running the app, so kindly update it in CONTRIBUTING. md . Tomorrow, I'll thoroughly examine the code and review it

**Comment by priyankarpal** [comment]
change `pnpm start` to `pnpm dev` in the CONTRIBUTING. md.

**Comment by dhawal-793** [comment]
I will update vite config.js and package.json and dokerfile tomorrow.
- vite config file to use old port.
- package.json to change the script  to use start command as most people are used to it.
- and also update the dokerfile to use port 3000 and use start command.

You can approve this pull request, or close this one so I can create a.new one tomorrow.

**Comment by priyankarpal** [comment]
> I will update vite config.js and package.json and dokerfile tomorrow.
> 
> * vite config file to use old port.
> * package.json to change the script  to use start command as most people are used to it.
> * and also update the dokerfile to use port 3000 and use start command.
> 
> You can approve this pull request, or close this one so I can create a.new one tomorrow.

No no don't close. You can edit it & I think there is no problem if we don't use port 3000

**Comment by dhawal-793** [comment]
> > I will update vite config.js and package.json and dokerfile tomorrow.
> > 
> > * vite config file to use old port.
> > * package.json to change the script  to use start command as most people are used to it.
> > * and also update the dokerfile to use port 3000 and use start command.
> > 
> > You can approve this pull request, or close this one so I can create a.new one tomorrow.
> 
> No no don't close. You can edit it & I think there is no problem if we don't use port 3000

As you said I haven't updated the port but I have updated the run command to be "start" instead of "dev".

**Comment by priyankarpal** [comment]
> > > I will update vite config.js and package.json and dokerfile tomorrow.
> > > 
> > > * vite config file to use old port.
> > > * package.json to change the script  to use start command as most people are used to it.
> > > * and also update the dokerfile to use port 3000 and use start command.
> > > 
> > > You can approve this pull request, or close this one so I can create a.new one tomorrow.
> > 
> > 
> > No no don't close. You can edit it & I think there is no problem if we don't use port 3000
> 
> As you said I haven't updated the port but I have updated the run command to be "start" instead of "dev".

okk sounds good 🎉

**Comment by priyankarpal** [comment]
@dhawal-793 I think it will work fine. Check your local setup & also share a demo if you want.

**Comment by dhawal-793** [comment]
> @dhawal-793 I think it will work fine. Check your local setup & also share a demo if you want.

Everything looks good in the local setup.
And about the website, nothing has changed as much.

This is the preview :
vite-preview

**Comment by priyankarpal** [comment]
> > @dhawal-793 I think it will work fine. Check your local setup & also share a demo if you want.
> 
> Everything looks good in the local setup. And about the website, nothing has changed as much.
> 
> This is the preview : vite-preview

Looks Good 🎉

**Review by priyankarpal — APPROVED** [review]
Thanks for your contributions 🎉 ❤️

**Comment by JasonDsouza212** [comment]
I have been trying to run your branch. 
Can you help me with installing dependencies and provide steps to run the project by editing the CONTRIBUTIONS.md file?

**Comment by dhawal-793** [comment]
> I have been trying to run your branch. Can you help me with installing dependencies and provide steps to run the project by editing the CONTRIBUTING. md file?

remove previous dependencies and run pnpm i to install and pnpm start to start the server

**Comment by JasonDsouza212** [comment]
Everything looks good. Good work, @dhawal-793

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
