### PR TITLE
chore: Added Fullstack.cafe #1460

### LINKED ISSUE #1346: [Adding Tool]: Fullstack.cafe for preparing for tech interviews :)
### What tool are you adding and to what category?

We need to add Fullstack.cafe for preparation for tech interviews.
i want to add this resource assign it to me under GSSoC 2023!!! 

### Add Tool Link

Add tool link [fullstack.cafe](https://www.fullstack.cafe/). Most of the questions are provided free and can be downloaded via pdf.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by Ujjwal-soni98**
## Related Issue

closes #1346

## Description

 Added the resource for tech-interview preparation.

## Screenshots

Screenshot 2023-07-22 232920

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Ujjwal-soni98** [comment]
hey @JasonDsouza212 Please tell me how to resolve this title formatting check

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the [CONTRIBUTING.md](https://github.com/JasonDsouza212/free-hit/blob/main/CONTRIBUTING.md) and change it accordingly.

**Comment by Ujjwal-soni98** [comment]
@JasonDsouza212 please review and merge it under GSSoC'2023
Thank You!!! 😊

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by Ujjwal-soni98** [comment]
Kindly Add GSSoC tag in that pull request 🙂🙂

**Comment by Ujjwal-soni98** [comment]
@JasonDsouza212 Please add Gssoc23 tag in the issue #1460 
Thank You!

**Pull request merged**
