### PR TITLE
Feature: added back To Top button

### PR DESCRIPTION
**Pull request by dhawal-793**
Merge Conflict Resolved

completes #151.

### CODE REVIEW

**Comment by dhawal-793** [comment]
@JasonDsouza212 Can you tell me what error occurred while deploying,
 I am trying to know what error occurred, but it is showing a 404 page.
 In my local environment, everything looks good, and there are no console errors either.

**Comment by dhawal-793** [comment]
> There seems to be some error, go through the code once

Fixed the issue, There was a problem with dependencies => react-lazy-load-image-component and react-scroll.
So I removed react-lazy-load-image-component and added react-lazyload

You can view the changes and suggest any changes If any.

**Comment by JasonDsouza212** [comment]
Good one @dhawal-793 can you add some screenshots

**Comment by JasonDsouza212** [comment]
@dhawal-793, which was a much-needed functionality. Can you set the height and width of the button to 3rem, and on mobile devices, let it be 2.5rem?

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by dhawal-793** [comment]
### On smaller devices (width < 768px)
small

**Comment by dhawal-793** [comment]
### On medium to large devices (width >= 768px)
large

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by dhawal-793** [comment]
> @dhawal-793, which was a much-needed functionality. Can you set the height and width of the button to 3rem, and on mobile devices, let it be 2.5rem?

Updated width and height for different devices

**Pull request merged**
