### PR TITLE
redesign home page buttons

### PR DESCRIPTION
**Pull request by sinhaniik**
Redesign the buttons to look and feel good

### CODE REVIEW

**Comment by sinhaniik** [comment]
yeah sure 
it is before i make any changes 
By Default : 
Screenshot (27)

On Hover : 
Screenshot (28)

After Changes 
Default : 
Screenshot (29)

On Hover : 
Screenshot (30)

**Comment by sinhaniik** [comment]
after 2 commit 
The header will look like this and these images act like the link you can click on it and it will redirect where the symbol suggests.
Screenshot (31)

**Comment by JasonDsouza212** [comment]
The problem with these changes is that the user may become confused when recognizing the buttons. However, the Github and Twitter icons look good, so let's keep them but reduce their size. They appear too large, so  try reducing their height and width.

**Comment by sinhaniik** [comment]
As you said the `size of the icon has been reduced` and for the button `changed the background-color and on hover border has been added  ` so that they connot mix with the main body 
Screenshot (32)

**Comment by JasonDsouza212** [comment]
The changes look amazing, but the mobile view is not like the old UI. Try making changes that resemble the old UI in the mobile view. Other than that, everything else looks good.

## The changes you made 
Screenshot from 2023-03-30 21-35-05

## Old UI
Screenshot from 2023-03-30 21-34-57

**Comment by sinhaniik** [comment]
as you said i make this `responsive to all screen sizes` 

Screenshot (33)

**Comment by JasonDsouza212** [comment]
Can you  upload screenshots of the mobile view?

**Comment by JasonDsouza212** [comment]
###  make this UI look the same as the old UI because the header and button sections look odd.
Screenshot from 2023-04-01 11-23-25

**Comment by sinhaniik** [comment]
here are the sc in different phones take a look
`pixel phones`
Screenshot (34)

`iphone XR`
Screenshot (35)

`samsung s20 ultra`
Screenshot (36)

**Pull request closed without merging**
