### PR TITLE
update new extension

### PR DESCRIPTION
**Pull request by Younus-Saberi**
🛠️Fix to issue #451 
✅Added and Updated the old Leetcode extension with the new Extension **LeetSync**

Edit:

Before Committing and pushing to the branch, I format the codebase with the `pnpm format` commands.

### CODE REVIEW

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
can you explain what are pnpm commands

**Comment by JasonDsouza212** [comment]
make only the change you mentioned. Do not make any other changes. If you want to make additional changes, please create a separate issue for each.

**Comment by Younus-Saberi** [comment]
@JasonDsouza212, Sure I have reverted back to one commit.
I applied and Done change according to my assigned issue #451 
Please review it and Provide me with your feedback

**Comment by JasonDsouza212** [comment]
There are conflicts in it that need to be resolved. Additionally, you made an issue only for editing the existing DB, so please focus on resolving that particular issue without making any other changes. One option is to create a new pull request with the necessary edits, or you can revert all changes back to the original state

**Pull request closed without merging**
