### PR TITLE
[style]: Font changed

### PR DESCRIPTION
**Pull request by kartikkc**
## Related Issue
Closes: #457 

## Description of Changes

- Changed the fonts.

## Screenshots 
|      Original       |       Updated        |
| :-----------------: | :------------------: |
| font-improvement|font-improvemed|
|font-improvement-2|font-improvemed-2|
|font-improvement-3|font-improvemed-3|
|font-improvement-4|font-improvemed-4|

### CODE REVIEW

**Review by amantank — APPROVED** [review]
LGTM

**Comment by JasonDsouza212** [comment]
@kartikkc , make the changes only for cards , rest of it be the same

**Review by amantank — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
If we don't receive a reply from @kartikkc within a day, we will close this PR.

**Comment by kartikkc** [comment]
> If we don't receive a reply from @kartikkc within a day, we will close this PR.

I have made the changes to the font for the cards only, and the rest I have reverted back to the normal.

**Comment by JasonDsouza212** [comment]
There are conflicts so resolve it , inorder to get merged

**Comment by JasonDsouza212** [comment]
Also add some screenshots

**Comment by JasonDsouza212** [comment]
As this pull request is inactive, I'll be closing it.

**Pull request closed without merging**
