### PR TITLE
improved UI of Error Page #417

### PR DESCRIPTION
**Pull request by Google-Ka-Dinosaur**
Hey there I have fixed issue #417 
Screenshot (206)
This is how the error page looks right now, on clicking the image the user will navigate back to the page from where he/she had come to this one. used this navigation to ensure that the user can just resume his/her work by going back rather than having to navigate back to the home page.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The changes you made are good, but our theme is white and black. Therefore, please change the image to one that aligns with the theme's style

**Comment by Google-Ka-Dinosaur** [comment]
@JasonDsouza212 I have made the changes.
Screenshot (207)

**Comment by Google-Ka-Dinosaur** [comment]
@JasonDsouza212 Kindly review the PR . I have made the changes

**Comment by JasonDsouza212** [comment]
can you add screenshots of the mobile view and PC

**Comment by Google-Ka-Dinosaur** [comment]
Screenshot (211)
Screenshot (216)
Screenshot (217)

**Comment by JasonDsouza212** [comment]
@Google-Ka-Dinosaur Also the background is white which is not the background of the Application

**Pull request closed without merging**
