### PR TITLE
feat : Added Shadow to Container (for cards)

### PR DESCRIPTION
**Pull request by itsarraj**
Added A Feature , Shadows to each container to beautify it .
before -
Screenshot from 2023-04-02 23-16-42
after - 
Screenshot from 2023-04-02 23-16-42

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
I'm not able to find any changes. @itsarraj  can you please point them out?

**Comment by itsarraj** [comment]
image

**Comment by itsarraj** [comment]
Added Shadow That has slight difference to find but it it improves once transition occur

**Comment by JasonDsouza212** [comment]
No, I'm not talking about the code. I'm saying that I'm not able to see any visual changes

**Comment by itsarraj** [comment]
There is visual Change , Focus on Corners of card when they make transition. Overall it looks good.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
