### PR TITLE
chore: added CodeGpt 

### LINKED ISSUE #766: [Feat]: Add New AI Tool to the list
### What feature?

- CodeGPT is a powerful coding assistance tool based on OpenAI's GPT-3.5 architecture.
- CodeGPT provides a range of functionalities that assist developers in various aspects of coding, including code completion, code explanations, code improvement suggestions, and code creation.

You can find more information about CodeGpt at https://codegpt.co/

### Add screenshots

image

<br> <br>
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by BALASARVAN12**
Add:Added AI CodeGpt website #766 
Closes #766 

## Description

- CodeGPT is a powerful coding assistance tool based on OpenAI's GPT-3.5 architecture.
- CodeGPT provides a range of functionalities that assist developers in various aspects of coding, including code completion, code explanations, code improvement suggestions, and code creation.
- Added info about CodeGPT in ai category of products.json

## Screenshots
image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the README.md and change it accordingly.

**Comment by BALASARVAN12** [comment]
@JasonDsouza212 i have changed the pr title

**Comment by priyankarpal** [comment]
> @JasonDsouza212 I have changed the pr title According to the readme file but the PR title format is causing an error in the workflow. can you please give a format for how to give the pr title

it will be `chore: added tools name`

**Comment by BALASARVAN12** [comment]
@JasonDsouza212 All checks have passed

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
