### PR TITLE
min-height added to bookmarks not found wrapper

### PR DESCRIPTION
**Pull request by rawasaditya**
I am dynamically calculating min-height based to height of device and total height of nav and footer. This changes make  responsive as well.
This pull request is against this  [488](https://github.com/JasonDsouza212/free-hit/issues/488)

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
can you add some screenshots and also resolve the conflicts @rawasaditya

**Comment by rawasaditya** [comment]
checkout for screen shots
Screenshot 2023-06-12 061705

**Comment by JasonDsouza212** [comment]
Please add a screen recording that allows us to view all the pages and how they appear across various media widths.

**Comment by JasonDsouza212** [comment]
As this pull request is inactive, I'll be closing it.

**Pull request closed without merging**
