### PR TITLE
issue #521

### PR DESCRIPTION
**Pull request by Once-kaur**
## Related Issue
#521 

Closes #issue_number

#521

## Description

An animated website preloader is added, which appears as the website is fully loaded before going to the main page
## Screenshots

image

image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
This has an issue , and also add a video

**Comment by Once-kaur** [comment]
Ok,can you pls tell what the issue is about and video is of page working in  description section of pr right?

**Comment by Once-kaur** [comment]
https://github.com/JasonDsouza212/free-hit/assets/95931242/26812c25-5cb4-4a84-aafe-11b1b5f55674

**Comment by JasonDsouza212** [comment]
There is a problem with implementing them in the project. When the animation increases, the application speed decreases. Therefore, I think it's better to keep the animation as it is.

**Comment by JasonDsouza212** [comment]
As this pull request is inactive, I'll be closing it.

**Pull request closed without merging**
