### PR TITLE
[GSSoC'23] Adding Movies websites 

### LINKED ISSUE #938: [Feat]: Movies Websites [GSSoC'23]
### What feature?

I have an idea 

I would like to add different movies websites like, movieverse, hdhub4u, and many more.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Related Issue - 938

Closes #938 

## Description
- Movieverse
- HD hub4u
- Movie mint

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@VenomFate-619 @JasonDsouza212 Sirs, please review this pr and requested to merge to a contribution under GSSoC'23 program

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney use URL shortener for Images

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 Sir i requested to add `level 2` on it.

Thanks for assigning this task to me.

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
