### PR TITLE
fix: improved lighthouse score

### LINKED ISSUE #1405: [Feat]: Enhancing Lighthouse Score for Improved Website Performance
### What feature?

Currently, our website's Lighthouse score falls short of the desired standards, which can affect its accessibility, speed, and overall usability. 
This issue aims to address the existing performance gaps and enhance the website's Lighthouse score to provide a smoother and more engaging experience for our visitors.

### Add screenshots

Screenshot (619)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Avinash905**
## Related Issue

Closes #1405 

## Description

Improved the accessibility, performance, seo, and implemented best practices

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Avinash905** [comment]
.

**Comment by VenomFate-619** [comment]
post the lighthouse score that you are getting after these changes.

**Comment by Avinash905** [comment]
> post the lighthouse score that you are getting after these changes.

Screenshot (785)

**Comment by VenomFate-619** [comment]
for me on local is coming different.

desktop
image


mobile
image

**Comment by JasonDsouza212** [comment]
@Avinash905, the performance is significantly lower on mobile devices compared to the production version of Free-hit. Additionally, I've noticed some bugs that need attention. For instance, when viewing Free-hit in mobile mode, the logo doesn't display correctly as it does in your changes, and it appears misaligned. Furthermore, there seems to be an extra space after the footer, which is not present in the current Free-hit version.

Please take care of these issues and also resolve any conflicts . After implementing all the changes, kindly provide a screen recording of the entire application to review the updates thoroughly. Additionally, attach the Lighthouse scores for both desktop and mobile devices so that we can proceed with the merge as soon as possible. Thank you!
Screenshot from 2023-07-24 17-40-04
Screenshot from 2023-07-24 17-39-56

**Comment by Avinash905** [comment]
- Aligned the logo on mobile screen
- Removed the gap below the footer 


**Desktop score:**

Screenshot (799)

<br/>

**Mobile score:**

Screenshot (800)

**Comment by JasonDsouza212** [comment]
@Avinash905, can you resolve the conflicts? I'll look into it thoroughly tomorrow.

**Comment by JasonDsouza212** [comment]
@Avinash905 
await fetch(`https://api.github.com/repos/JasonDsouza212/free-hit/contributors?per_page=100`) Temporary merge branch 2

can you explain this line and
const response = await fetch('DB/product.json', {credentials: 'omit'})

this line

**Comment by Avinash905** [comment]
> @Avinash905 await fetch(`https://api.github.com/repos/JasonDsouza212/free-hit/contributors?per_page=100`) Temporary merge branch 2
> 
> can you explain this line and const response = await fetch('DB/product.json', {credentials: 'omit'})
> 
> this line

credentials: 'omit' is for not sending or receiving cookies. Because we are just fetching the data from the json file present in our repo.
And I have removed 'Temporary merge branch 2' which was added because I used github browser to resolve the conflicts.

**Comment by JasonDsouza212** [comment]
@Avinash905 Everything looks fine but there is a small bug
Screenshot from 2023-07-30 22-29-15
The delete button is larger than visit button

**Comment by Avinash905** [comment]
> @Avinash905 Everything looks fine but there is a small bug Screenshot from 2023-07-30 22-29-15 The delete button is larger than visit button

Changed it.

**Comment by JasonDsouza212** [comment]
> > @Avinash905 Everything looks fine but there is a small bug Screenshot from 2023-07-30 22-29-15 The delete button is larger than visit button
> 
> Changed it.
The height of delete button still varies

**Comment by Avinash905** [comment]
@JasonDsouza212 In this deployment https://free-r1a8o2att-jasondsouza212.vercel.app/ it is looking fine to me.

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
