### PR TITLE
Added devChallenges, frontendpractice, javascript30, codewars websites to free-hit 

### LINKED ISSUE #596: [Feat]: Adding website for developer for practice purpose
### Currently, the list of websites available on free-hit.com for developers to practice and learn is limited. I would like to propose the addition of the following websites to provide more resources for developers:

1. **devChallenges.io:** devChallenges.io is a platform that offers real-life projects for developers to work on and improve their skills. It provides a wide range of challenges across different technologies and skill levels.

2. **Frontend Practice**: Frontend Practice is a website that offers coding exercises focused specifically on frontend development. It covers various topics such as HTML, CSS, and JavaScript, allowing developers to sharpen their frontend skills.

3. **JavaScript30**: JavaScript30 is a free 30-day coding challenge created by Wes Bos. Each day, developers receive a new JavaScript project to build, accompanied by video tutorials. It helps developers strengthen their JavaScript skills through hands-on practice.

4. **Codewars**: Codewars is an online community-driven platform that provides coding challenges in multiple programming languages. Developers can solve these challenges to improve their problem-solving abilities and learn from others' solutions.

**Can you please assign this issue to me? So that I can add this website to free-hit.**

### Add screenshots

Add screenshots

**1. devChallenges.io**
dev

**2. Frontend Practice**
frontend practice

**3. JavaScript30**
javaScript 30

**4. Codewars**
code wares

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Prajwal0225**
## Related Issue

Closes #596 

## Description
I added devChallenges, frontendpractice, javascript30, codewars websites to free-hit

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by VenomFate-619** [comment]
image URL should be shortened, do read `contribution.md`

**Comment by JasonDsouza212** [comment]
@Prajwal0225 make sure to include only the mentioned tools and nothing else. Please thoroughly read the README.md file before creating a pull request.

**Comment by Prajwal0225** [comment]
I will make url shortened and then make a pr.

Sorry for the inconveniences 🥲

**Comment by JasonDsouza212** [comment]
> I will make url shortened and then make a pr.
> 
> Sorry for the inconveniences smiling_face_with_tear

Please revert the changes in the PR that modify indentation and the package file version as well.

**Pull request closed without merging**
