### PR TITLE
Added 3 more products to list

### PR DESCRIPTION
**Pull request by Abhinavcode13**
zarla , animoto and zety these are added

closes issue number #467

### CODE REVIEW

**Review by Abhinavcode13 — COMMENTED** [review]
please review

**Comment by JasonDsouza212** [comment]
Are all the tools you added free? Also, please add the "Zety" tool to the resume category.

**Comment by Abhinavcode13** [comment]
Yes they all are free

**Comment by Abhinavcode13** [comment]
@JasonDsouza212

**Comment by Abhinavcode13** [comment]
yeah updated it @JasonDsouza212

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
