### PR TITLE
Add free website tools

### PR DESCRIPTION
**Pull request by samailamalima**
Added three website tools

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
Looks good, but try to keep the description to a maximum of 12 words

**Comment by JasonDsouza212** [comment]
And also, pull the latest changes before working on it.

**Comment by priyankarpal** [comment]
This branch has conflicts please solve it.

**Comment by Bharadwajshivam28** [comment]
@JasonDsouza212 If it is not complete then can i complete this and make a pull request

**Comment by JasonDsouza212** [comment]
@Bharadwajshivam28 yes you can start working on this

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 yes you can start working on this

thanks

**Comment by Bharadwajshivam28** [comment]
can you give me the website link and under which category

**Comment by Bharadwajshivam28** [comment]
> can you give me the website link and under which category

@JasonDsouza212

**Pull request closed without merging**
