### PR TITLE
About  page updated

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have updated the about  page of the website by adding .

https://github.com/JasonDsouza212/free-hit/assets/132778037/e8ade548-cf69-43ed-b130-f212baa578fe

Kindly review and inform me if you wanna any other changes.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.

**Comment by Pragati-3003** [comment]
> @Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.
Okie, so basically I have to remove all hover effects and to reduce the gap, right?

**Comment by Anubhav6205** [comment]
> @Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.

Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by JasonDsouza212** [comment]
> > @Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.
> 
> Please assign me this issue so that I can resolve it under GSSOC-23

As of now, @Pragati-3003 is working on this. However, there are several other unassigned issues that you can check and work on.

**Comment by Pragati-3003** [comment]
> > > @Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.
> > 
> > 
> > Please assign me this issue so that I can resolve it under GSSOC-23
> 
> As of now, @Pragati-3003 is working on this. However, there are several other unassigned issues that you can check and work on.

I have changed ,please check.

> > > @Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.
> > 
> > 
> > aboutt Is it fine ? Kindly inform me if you wanna any other changes.
> 
> You only change the margin top, but you have also been trying to add the header, which is not required.

I have reduced the margin top ,please check.

**Comment by JasonDsouza212** [comment]
> > > @Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.
> > 
> > 
> > aboutt Is it fine ? Kindly inform me if you wanna any other changes.
> 
> You only change the margin top, but you have also been trying to add the header, which is not required.

@Pragati-3003 I have mentioned to you not to add the header About Us

**Comment by Pragati-3003** [comment]
> > > > @Pragati-3003, we would like the app to be kept simple. However, the changes you made are not aligning with our vision, so we cannot merge the issue. One thing you can do is reduce the gap at the beginning of the 'About' page slightly, and then I will be able to merge it.
> > > 
> > > 
> > > aboutt Is it fine ? Kindly inform me if you wanna any other changes.
> > 
> > 
> > You only change the margin top, but you have also been trying to add the header, which is not required.
> 
> @Pragati-3003 I have mentioned to you not to add the header About Us

I have already removed the header. 
Check commit 912651c.

**Pull request closed without merging**
