### PR TITLE
chore: added coding websites #1189

### LINKED ISSUE #1189: [Adding Tool]: Open source programs websites
### What tool are you adding and to what category?

We need to add

- MLH fellowship,
- Open summer of Code
- 24 pull requests, etc.

I would to add such open source websites links

### Add Tool Link

Add tool link

image

[MLH fellowship](https://fellowship.mlh.io/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] The tool is free for use

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Related Issue - 1189

Closes #1189 

## Description
- Google summer of Code
- Girl Script summer of Code
- Open summer of Code
- MLH Fellowship program
- 24 Pull requests

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please review this pull request

**Review by VenomFate-619 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney, I'm not getting what these categories are supposed to be.

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney , the category should contain at least 8 tools in it and you also need to add the category with this PR itself

**Comment by Avdhesh-Varshney** [comment]
@JasonDsouza212 @VenomFate-619 sir, please again review this pr

**Comment by Avdhesh-Varshney** [comment]
@VenomFate-619 @JasonDsouza212 sir, please again review this PR. I have added category into it and also added 3 more websites.

**Comment by JasonDsouza212** [comment]
@Avdhesh-Varshney , there are still some places where you need to update the category

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney , there are still some places where you need to update the category

Sir, please can you tell me those files, where i should update the category ?

**Pull request closed without merging**
