### PR TITLE
feat: Programiz

### LINKED ISSUE #887: [Feat]: Add Programiz for Learning and Practicing Code Better in Demanding Technologies is Free
### Feature Description:
- **`Add Programiz for Learning and Practicing Code Better in Demanding Technologies is Free`**

### Add screenshots

Add screenshots:
freehit-7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Related Issue

Closes #887 

## Description

- Add Programiz Website with Update Description Details in DB product.json File

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@NarendraKoya999, you are only allowed to work on one PR at a time. Therefore, I will be closing the rest of the PRs. Please refrain from creating new PRs until the current one is merged. You may create additional PRs only after the older PRs have been merged.

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999, you are only allowed to work on one PR at a time. Therefore, I will be closing the rest of the PRs. Please refrain from creating new PRs until the current one is merged. You may create additional PRs only after the older PRs have been merged.

Definitely I can Follow Your Guidelines @JasonDsouza212

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 your Json file has some errors , so look into it

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 your Json file has some errors , so look into it

Actually, I am missing Closing CXurly Brace in Programiz Object. I solved It now. Please check @JasonDsouza212

**Comment by JasonDsouza212** [comment]
@NarendraKoya999 you still need to correct the JSON file

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 you still need to correct the JSON file

I will check what actual Error @JasonDsouza212

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
