### PR TITLE
#82 : Add some tools to extensions

### PR DESCRIPTION
**Pull request by dhawal-793**
Updated some tools to be included in extensions category.

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by JasonDsouza212** [comment]
also add wordtune to extentions

**Comment by dhawal-793** [comment]
> also add wordtune to extentions

But wordtune is not an extension

**Comment by dhawal-793** [comment]
Creating new pull request.

**Comment by priyankarpal** [comment]
> Creating new pull request.

you can edit it.

**Pull request closed without merging**
