### PR TITLE
Add Trello and Mixkit to the tools category

### PR DESCRIPTION
**Pull request by AhorIsaac**
Issue Number 
#564

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
The branch has conflicts @AhorIsaac

**Review by JasonDsouza212 — APPROVED** [review]

**Comment by JasonDsouza212** [comment]
@AhorIsaac resolve the conflicts

**Comment by AhorIsaac** [comment]
I have resolve the conflicts

**Comment by JasonDsouza212** [comment]
@AhorIsaac, there have been some changes in the documentation regarding the rules to be followed during the PR. Please review it and make the necessary modifications. Also, remember to link an issue to the PR.

**Pull request merged**
