### PR TITLE
fix: image issue #1539

### PR DESCRIPTION
**Pull request by biplavmz**
image issue  #1539 

before :- 

image

After :- 
image

we can also increase the height and width as we are giving condition on the basis of image height

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@biplavmz can you walk me through the process

**Comment by biplavmz** [comment]
hii @JasonDsouza212 

so here
i am just getting the actual image height because every image has different height 
so according to that only i am giving the conditions  and give the classname 
which is required.

I am trying with only css but it's difficult because images are not proper.

**Comment by JasonDsouza212** [comment]
@biplavmz THE 9 ANIME and 100L5 logo looks small which is not as planned

**Comment by JasonDsouza212** [comment]
@biplavmz, if you are looking for a contribution opportunity, you could consider adding a feature that displays a modal upon successful bookmarking or deleting. This would enhance the user experience and provide more informative feedback.

**Comment by biplavmz** [comment]
ok @JasonDsouza212

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
