### PR TITLE
fix: made the dark mode button available on all pages #1142

### LINKED ISSUE #1142: [Feat]: Dark mode button on navbar
### What feature?

I have an idea to add a dark mode button on the navbar because currently, the dark mode button is not accessible from other pages such as bookmarks and about pages. Please assign me this issue. Thank you!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sumitkr2000**
## Related Issue

Closes #1142 

## Description

Hey @JasonDsouza212 I have made the dark mode button available on all the pages. I have created a separate component for the dark mode button to make it available globally. I have also changed the icon and styling to make it more user interactive. Please review my pr and merge it. Thank you!

## Screenshots

**Before:-**
image

**After:-**
image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@sumitkr2000 Everything is good but can you also change the color of the moon and Sun accordingly when clicked

**Comment by sumitkr2000** [comment]
@JasonDsouza212 which colour do you want. Can you please tell me colour of sun and moon. Right now also it is changing the colour

**Comment by JasonDsouza212** [comment]
As same as it looks in the Free-hit

**Comment by sumitkr2000** [comment]
@JasonDsouza212 Now is it good?

**Comment by JasonDsouza212** [comment]
@sumitkr2000 add some screen recording in all media widths

**Comment by sumitkr2000** [comment]
@JasonDsouza212 Please check the video

**Review by JasonDsouza212 — APPROVED** [review]

**Pull request merged**
