### PR TITLE
feat: Cards Improvements + Button Improvements 

### LINKED ISSUE #1395: Improve the cards
### What's the style idea?

image
I want to improve ui of the cards. Please assign it to me under gssoc'23

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by akanksha984**
## Related Issue

Closes #1395 

## Description

I have improved the ui of the cards, its hover effects and button, In both light and dark mode. 
Hope you like the changes. @JasonDsouza212 

## Screenshots

image
image
image
image

## Checklist

- [ X] My code adheres to the established style guidelines of the project.
- [ X] I have included comments in areas that may be difficult to understand.
- [ X] My changes have not introduced any new warnings.
- [ ]X I have conducted a self-review of my code.

### CODE REVIEW

**Comment by akanksha984** [comment]
@JasonDsouza212 please check it

**Comment by JasonDsouza212** [comment]
The PR title format you are using is causing an error in the workflow. Please follow the instructions in the [CONTRIBUTING.md](https://github.com/JasonDsouza212/free-hit/blob/main/CONTRIBUTING.md) and change it accordingly.

**Comment by JasonDsouza212** [comment]
give a space after feat:

**Comment by akanksha984** [comment]
@JasonDsouza212 thank you I have updated the title, now you may review it

**Comment by JasonDsouza212** [comment]
@akanksha984, the current free-hit design looks good, but I would like you to work on the dark mode. The shadow doesn't appear quite right, and there are several other parts in dark mode that need enhancement. Could you please work on that?

**Comment by akanksha984** [comment]
I have been assigned by you to improve the cards and buttons and in my case I have improved the shadow in darkmode as well so that it looks not very filled, Does it not look good?
And what more enhancements ? @JasonDsouza212

**Comment by JasonDsouza212** [comment]
@akanksha984, during the designing phase, we should discuss first what changes we are planning to make. This will give us clarity on what to expect in the updates. As I saw the changes, they look good but seem a bit minimalistic. Therefore, I suggest focusing more on the dark mode, as I noticed that the UI doesn't look good in dark mode. Improving it could make a valuable contribution from your side.

**Comment by akanksha984** [comment]
@JasonDsouza212 Can you suggest what type of changes needs to be done ?
Should I increase the shadow effect ? Or should I keep the shadow more and on hover it increases ?

**Comment by JasonDsouza212** [comment]
@akanksha984, in the dark mode of the production Free-hit application, we can see that the box shadow does not look good. Could you please take care of that? Additionally, the "back to top" and "dark/light theme" buttons are not aligned in the same line in mobile views. It would be great if you could address this issue as well. Thank you!

**Pull request closed without merging**
