### PR TITLE
Website changelog

### PR DESCRIPTION
**Pull request by priyankarpal**
## Changelog 💥

* removed previous buttons styles
* added new style 
* button wrapper removed
* `title=""` removed
* removed `<div class="button-wrapper">`
* also, extra code removed
* bitly image link, the title changed
* directions changed
* added products after the header
* root colour added
* css code minified
* added emojis
* added footer credits
* changed footer styles
* removed `to.uppercase`
* added new button styles
* removed a duplicate product 
* bug fixed
* added new nav links

### Before fixing the problem 👇

https://user-images.githubusercontent.com/88102392/220247747-64d92b88-c746-457b-ac29-e89183c1f0d6.mp4

### After fixing the problem 😎

https://user-images.githubusercontent.com/88102392/220247928-1caf924c-f58d-46a0-bf83-b6f2e37eb4af.mp4

# Full website looks

https://user-images.githubusercontent.com/88102392/220248058-b0f067ec-3da1-48b2-ba68-b6161782bea6.mp4

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
It looks amazing @priyankarpal. Can you make the buttons a little more attractive

**Comment by priyankarpal** [comment]
> It looks amazing @priyankarpal. Can you make the buttons a little more attractive 

Ok.

**Comment by priyankarpal** [comment]
hi, @JasonDsouza212 I lost my code so I can't update the buttons. Could you merge it? so that I can get my code.

**Comment by JasonDsouza212** [comment]
You can pull it from your fork

**Pull request closed without merging**
