### PR TITLE
Name logo of FreeHit Website

### PR DESCRIPTION
**Pull request by Tisha6661**
## Related Issue
Designed the name logo of the website.

Closes #issue_number
#804 

## Description
Added the logo.

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
@Tisha6661, let's first discuss the details, and then we can proceed with the implementation.

**Comment by Tisha6661** [comment]
@JasonDsouza212 Sure, Is there any issue?

**Comment by Tisha6661** [comment]
@JasonDsouza212 Are the colors alright, I only need to work on design right?

**Comment by JasonDsouza212** [comment]
Hello, contributors! This is Jason speaking. Due to some workflow issues, we will be closing all the PRs today. Therefore, I kindly request all of you to create new PRs tomorrow, as the currently open ones will be closed by our team. I apologize for any inconvenience caused. Also, please make sure to check the titles when creating the PRs. You can refer to the README.md for more details. Thank you.

**Pull request closed without merging**
